/* global window */
(() => {
  "use strict";

  /**
   * Full-sentence pairs for structure practice (English ↔ Spanish word order).
   * { en, es, tag? }
   */
  window.SENTENCE_BANK = [
    { en: "Why are you calling me?", es: "¿Por qué me estás llamando?", tag: "questions" },
    { en: "What are you doing here?", es: "¿Qué haces aquí?", tag: "questions" },
    { en: "Where did you put my keys?", es: "¿Dónde pusiste mis llaves?", tag: "questions" },
    { en: "When are we leaving?", es: "¿Cuándo nos vamos?", tag: "questions" },
    { en: "How much does this cost?", es: "¿Cuánto cuesta esto?", tag: "questions" },
    { en: "Who told you that?", es: "¿Quién te dijo eso?", tag: "questions" },
    { en: "Why didn't you say anything?", es: "¿Por qué no dijiste nada?", tag: "negation" },
    { en: "I don't know him.", es: "No lo conozco.", tag: "clitics" },
    { en: "I haven't seen her today.", es: "No la he visto hoy.", tag: "clitics" },
    { en: "She gave it to me yesterday.", es: "Me lo dio ayer.", tag: "clitics" },
    { en: "I'm buying them for you.", es: "Te los compro.", tag: "clitics" },
    { en: "We told them the truth.", es: "Les dijimos la verdad.", tag: "clitics" },
    { en: "I like chocolate.", es: "Me gusta el chocolate.", tag: "gustar" },
    { en: "She loves music.", es: "Le encanta la música.", tag: "gustar" },
    { en: "It bothers me when you're late.", es: "Me molesta cuando llegas tarde.", tag: "gustar" },
    { en: "We're interested in the offer.", es: "Nos interesa la oferta.", tag: "gustar" },
    { en: "I'm looking for my phone.", es: "Busco mi teléfono.", tag: "no pronoun" },
    { en: "I'm looking for it.", es: "Lo busco.", tag: "clitics" },
    { en: "She's reading the book.", es: "Ella lee el libro.", tag: "SVO" },
    { en: "She's reading it.", es: "Lo lee.", tag: "clitics" },
    { en: "I need to tell you something.", es: "Necesito decirte algo.", tag: "infinitive + pronoun" },
    { en: "I want you to listen.", es: "Quiero que escuches.", tag: "subjunctive" },
    { en: "It's important that you come.", es: "Es importante que vengas.", tag: "subjunctive" },
    { en: "I'm glad you're here.", es: "Me alegra que estés aquí.", tag: "subjunctive" },
    { en: "Maybe he'll call later.", es: "Quizá llame más tarde.", tag: "subjunctive" },
    { en: "I don't think it's true.", es: "No creo que sea verdad.", tag: "subjunctive" },
    { en: "Can you help me?", es: "¿Puedes ayudarme?", tag: "questions" },
    { en: "Could you speak more slowly?", es: "¿Podrías hablar más despacio?", tag: "questions" },
    { en: "Do you mind if I sit here?", es: "¿Te importa si me siento aquí?", tag: "questions" },
    { en: "I have to leave now.", es: "Tengo que irme ahora.", tag: "reflexive" },
    { en: "We got up early.", es: "Nos levantamos temprano.", tag: "reflexive" },
    { en: "She sat down next to me.", es: "Se sentó a mi lado.", tag: "reflexive" },
    { en: "They forgot to call.", es: "Se olvidaron de llamar.", tag: "reflexive" },
    { en: "I'm going to study tonight.", es: "Voy a estudiar esta noche.", tag: "future" },
    { en: "I'll call you tomorrow.", es: "Te llamaré mañana.", tag: "future" },
    { en: "It was raining when I arrived.", es: "Llovía cuando llegué.", tag: "time clause" },
    { en: "After we eat, we'll go out.", es: "Después de comer, saldremos.", tag: "time clause" },
    { en: "Before you leave, turn off the light.", es: "Antes de irte, apaga la luz.", tag: "commands" },
    { en: "Don't open the door.", es: "No abras la puerta.", tag: "commands" },
    { en: "Tell me the truth.", es: "Dime la verdad.", tag: "commands" },
    { en: "Let's go!", es: "¡Vámonos!", tag: "commands" },
    { en: "There are many people here.", es: "Hay mucha gente aquí.", tag: "hay" },
    { en: "There isn't any milk left.", es: "No queda leche.", tag: "existential" },
    { en: "I have two brothers.", es: "Tengo dos hermanos.", tag: "tener" },
    { en: "I'm hungry.", es: "Tengo hambre.", tag: "tener" },
    { en: "She's thirty years old.", es: "Ella tiene treinta años.", tag: "tener" },
    { en: "This is the book I was talking about.", es: "Este es el libro del que hablaba.", tag: "relative" },
    { en: "That's the woman who helped us.", es: "Esa es la mujer que nos ayudó.", tag: "relative" },
    { en: "I work in order to save money.", es: "Trabajo para ahorrar dinero.", tag: "para" },
    { en: "Thanks for coming.", es: "Gracias por venir.", tag: "por vs para" },
    { en: "I'm worried about the exam.", es: "Estoy preocupado por el examen.", tag: "prepositions" },
    { en: "It depends on the weather.", es: "Depende del tiempo.", tag: "prepositions" },
    { en: "I've never been to Spain.", es: "Nunca he estado en España.", tag: "negation" },
    { en: "Nobody called.", es: "No llamó nadie.", tag: "negation" },
    { en: "I don't want anything.", es: "No quiero nada.", tag: "negation" },
    { en: "Neither do I.", es: "Yo tampoco.", tag: "agreement" },
    { en: "Me too.", es: "Yo también.", tag: "agreement" },
    { en: "The more you practice, the easier it gets.", es: "Cuanto más practicas, más fácil se vuelve.", tag: "comparative" },
    { en: "As soon as I finish, I'll write to you.", es: "En cuanto termine, te escribo.", tag: "time clause" },
    { en: "Unless it rains, we'll go to the park.", es: "A menos que llueva, iremos al parque.", tag: "subjunctive" },
    { en: "So that you understand, I'll explain again.", es: "Para que entiendas, lo explico otra vez.", tag: "subjunctive" },
    { en: "I doubt they'll arrive on time.", es: "Dudo que lleguen a tiempo.", tag: "subjunctive" },
    { en: "It's the best movie I've ever seen.", es: "Es la mejor película que he visto nunca.", tag: "superlative" },
    { en: "She speaks Spanish better than I do.", es: "Ella habla español mejor que yo.", tag: "comparison" },
    { en: "I'm taller than my brother.", es: "Soy más alto que mi hermano.", tag: "comparison" },
    { en: "They arrived two hours ago.", es: "Llegaron hace dos horas.", tag: "time" },
    { en: "See you in a week.", es: "Nos vemos dentro de una semana.", tag: "time" },
    { en: "I've lived here since 2020.", es: "Vivo aquí desde 2020.", tag: "time" },
    { en: "During the trip we slept little.", es: "Durante el viaje dormimos poco.", tag: "time" },
    { en: "According to the news, it's true.", es: "Según las noticias, es verdad.", tag: "discourse" },
    { en: "In my opinion, it's a bad idea.", es: "En mi opinión, es una mala idea.", tag: "discourse" },
    { en: "By the way, did you call?", es: "Por cierto, ¿llamaste?", tag: "discourse" },
    { en: "Actually, I changed my mind.", es: "En realidad, cambié de opinión.", tag: "discourse" },
    { en: "Even though it was late, we stayed.", es: "Aunque era tarde, nos quedamos.", tag: "concession" },
    { en: "If I were you, I wouldn't go.", es: "Si yo fuera tú, no iría.", tag: "conditional" },
    { en: "If you heat it, it melts.", es: "Si lo calientas, se derrite.", tag: "conditional" },
    { en: "I would help you if I could.", es: "Te ayudaría si pudiera.", tag: "conditional" },
    { en: "What would you do in my place?", es: "¿Qué harías en mi lugar?", tag: "conditional" },
    { en: "You should see a doctor.", es: "Deberías ir al médico.", tag: "advice" },
    { en: "You mustn't smoke here.", es: "No debes fumar aquí.", tag: "obligation" },
    { en: "You can leave your bag here.", es: "Puedes dejar tu bolsa aquí.", tag: "permission" },
    { en: "We might arrive late.", es: "Quizá lleguemos tarde.", tag: "probability" },
    { en: "She must be tired.", es: "Debe de estar cansada.", tag: "probability" },
    { en: "The keys are on the table.", es: "Las llaves están encima de la mesa.", tag: "estar" },
    { en: "The meeting is at three.", es: "La reunión es a las tres.", tag: "ser" },
    { en: "He's a teacher.", es: "Él es profesor.", tag: "ser" },
    { en: "He's sick today.", es: "Él está enfermo hoy.", tag: "estar" },
    { en: "I'm going to the store.", es: "Voy a la tienda.", tag: "motion" },
    { en: "I'm fine, thanks.", es: "Estoy bien, gracias.", tag: "estar" },
    { en: "What is your name?", es: "¿Cómo te llamas?", tag: "questions" },
    { en: "My name is Ana.", es: "Me llamo Ana.", tag: "introductions" },
    { en: "Nice to meet you.", es: "Mucho gusto.", tag: "introductions" },
    { en: "I don't understand you.", es: "No te entiendo.", tag: "clitics" },
    { en: "Can you repeat that?", es: "¿Puedes repetir eso?", tag: "questions" },
    { en: "I speak a little Spanish.", es: "Hablo un poco de español.", tag: "introductions" },
    { en: "Do you speak English?", es: "¿Hablas inglés?", tag: "questions" },
    { en: "I'm from the United States.", es: "Soy de Estados Unidos.", tag: "introductions" },
    { en: "How long have you been waiting?", es: "¿Cuánto tiempo llevas esperando?", tag: "questions" },
    { en: "I've been waiting for ten minutes.", es: "Llevo diez minutos esperando.", tag: "structure" },
    { en: "It took me an hour to get there.", es: "Tardé una hora en llegar.", tag: "structure" },
    { en: "I spent the whole day studying.", es: "Pasé el día entero estudiando.", tag: "structure" },
    { en: "I made her laugh.", es: "La hice reír.", tag: "clitics" },
    { en: "We heard them leave.", es: "Los oímos salir.", tag: "clitics" },
    { en: "Let me think.", es: "Déjame pensar.", tag: "commands" },
    { en: "I'll see you later.", es: "Te veo luego.", tag: "farewells" },
    { en: "See you tomorrow.", es: "Hasta mañana.", tag: "farewells" },
    { en: "Have a good trip.", es: "Buen viaje.", tag: "farewells" },
    { en: "Congratulations on your new job.", es: "Enhorabuena por tu nuevo trabajo.", tag: "social" },
    { en: "I'm sorry for your loss.", es: "Lo siento por tu pérdida.", tag: "social" },
    { en: "No problem at all.", es: "No hay ningún problema.", tag: "social" },
    { en: "It's none of my business.", es: "No es asunto mío.", tag: "social" },
    { en: "Mind your own business.", es: "Métete en tus asuntos.", tag: "social" },
    { en: "Whatever you say.", es: "Lo que tú digas.", tag: "social" },
    { en: "That's not what I meant.", es: "Eso no es lo que quería decir.", tag: "clarification" },
    { en: "In other words, we agree.", es: "En otras palabras, estamos de acuerdo.", tag: "discourse" },
    { en: "First we'll eat, then we'll decide.", es: "Primero comeremos, luego decidiremos.", tag: "sequence" },
    { en: "Not only did he arrive late, he forgot the documents.", es: "No solo llegó tarde, sino que olvidó los documentos.", tag: "emphasis" },
    { en: "I neither know nor care.", es: "Ni lo sé ni me importa.", tag: "negation" },
    { en: "The less you say, the better.", es: "Cuanto menos digas, mejor.", tag: "comparative" },
    { en: "Whoever wants to come is welcome.", es: "Quien quiera venir es bienvenido.", tag: "relative" },
    { en: "Whatever happens, we'll be fine.", es: "Pase lo que pase, estaremos bien.", tag: "subjunctive" },
    { en: "Wherever you go, I'll follow.", es: "Dondequiera que vayas, te seguiré.", tag: "subjunctive" },
    { en: "However you look at it, it's expensive.", es: "Comoquiera que lo mires, es caro.", tag: "subjunctive" },
    { en: "When I was a child, I played in the park.", es: "Cuando era niño, jugaba en el parque.", tag: "preterite vs imperfect" },
    { en: "Yesterday I played soccer for two hours.", es: "Ayer jugué al fútbol durante dos horas.", tag: "preterite" },
    { en: "I was studying when you called.", es: "Estudiaba cuando llamaste.", tag: "preterite vs imperfect" },
    { en: "It's been three years since I started.", es: "Hace tres años que empecé.", tag: "hace que" },
    { en: "I've known him since we were kids.", es: "Lo conozco desde que éramos niños.", tag: "desde que" },
    { en: "I told him not to come.", es: "Le dije que no viniera.", tag: "reported speech · subjunctive" },
    { en: "She asked me where I was going.", es: "Me preguntó adónde iba.", tag: "indirect question" },
    { en: "I'm afraid he won't come.", es: "Tengo miedo de que no venga.", tag: "emotion + subjunctive" },
    { en: "I'll wait until he arrives.", es: "Esperaré hasta que llegue.", tag: "temporal + subjunctive" },
    { en: "Bring it to me.", es: "Tráemelo.", tag: "commands · clitics" },
    { en: "Don't tell her.", es: "No se lo digas.", tag: "commands · clitics" },
    { en: "Let's tell them everything.", es: "Contémosles todo.", tag: "commands · clitics" },
    { en: "I gave it to her yesterday.", es: "Se lo di ayer.", tag: "clitics" },
    { en: "I'm thinking about buying a car.", es: "Estoy pensando en comprar un coche.", tag: "gerund + prep" },
    { en: "After having eaten, we left.", es: "Después de haber comido, nos fuimos.", tag: "compound infinitive" },
    { en: "The book I read is good.", es: "El libro que leí es bueno.", tag: "relative clause" },
    { en: "The city where I live is small.", es: "La ciudad donde vivo es pequeña.", tag: "relative · donde" },
    { en: "There's nothing to do.", es: "No hay nada que hacer.", tag: "relative + infinitive" },
    { en: "I need something to drink.", es: "Necesito algo para beber.", tag: "para + infinitive" },
    { en: "It's the first time I've been here.", es: "Es la primera vez que he estado aquí.", tag: "perfect · time" },
    { en: "He works as a waiter.", es: "Trabaja de camarero.", tag: "de + profession" },
    { en: "They left without saying goodbye.", es: "Se fueron sin despedirse.", tag: "sin + infinitive" },
    { en: "I'm learning to drive.", es: "Estoy aprendiendo a conducir.", tag: "a + infinitive" },
    { en: "I forgot to lock the door.", es: "Me olvidé de cerrar la puerta.", tag: "reflexive + de" },
    { en: "I try not to worry.", es: "Intento no preocuparme.", tag: "negation + infinitive" },
    { en: "What if we go tomorrow?", es: "¿Y si vamos mañana?", tag: "suggestions" },
    { en: "I have nothing to say.", es: "No tengo nada que decir.", tag: "negation" },
    { en: "Who is it for?", es: "¿Para quién es?", tag: "question + preposition" },
    { en: "The more I study, the more I forget.", es: "Cuanto más estudio, más olvido.", tag: "comparative correlation" },
    { en: "As far as I know, it's closed.", es: "Hasta donde yo sé, está cerrado.", tag: "discourse" },
    { en: "Provided you behave, you may go out.", es: "Siempre que te portes bien, puedes salir.", tag: "subjunctive · condition" },
    { en: "I suggest we leave early.", es: "Sugiero que salgamos temprano.", tag: "subjunctive · suggestion" },
    { en: "It's weird that he isn't here.", es: "Es raro que no esté aquí.", tag: "subjunctive · judgment" },
    { en: "I hope you feel better.", es: "Espero que te mejores.", tag: "subjunctive · hope" },
    { en: "Perhaps she's right.", es: "Tal vez tenga razón.", tag: "subjunctive · doubt" },
    { en: "Make yourself at home.", es: "Siéntete como en casa.", tag: "reflexive · command" },
    { en: "I can't wait to see you.", es: "Tengo muchas ganas de verte.", tag: "tener ganas de" },
    { en: "I don't know if he'll come.", es: "No sé si vendrá.", tag: "indicative · future probability" },
    { en: "I doubt that it's true.", es: "Dudo que sea verdad.", tag: "subjunctive · doubt" },
    { en: "It's true that he's tired.", es: "Es verdad que está cansado.", tag: "indicative · fact" },
    { en: "They made us wait an hour.", es: "Nos hicieron esperar una hora.", tag: "causative · clitics" },
    { en: "I had already eaten when they arrived.", es: "Ya había comido cuando llegaron.", tag: "pluperfect" },
    { en: "We'll see each other soon.", es: "Nos veremos pronto.", tag: "reciprocal · future" },
    { en: "She got angry at me.", es: "Se enfadó conmigo.", tag: "reflexive · emotion" },
    { en: "I'm used to getting up early.", es: "Estoy acostumbrado a levantarme temprano.", tag: "acostumbrarse a" },
    { en: "He stopped smoking last year.", es: "Dejó de fumar el año pasado.", tag: "dejar de + inf" },
    { en: "She keeps talking during class.", es: "Sigue hablando durante la clase.", tag: "seguir + gerund" },
    { en: "I returned the book to the library.", es: "Devolví el libro a la biblioteca.", tag: "preterite · indirect object" },
    { en: "Give me five minutes.", es: "Dame cinco minutos.", tag: "command · indirect" },
    { en: "Write it down for me.", es: "Escríbemelo.", tag: "command · clitics" },
    { en: "It's better for you to stay.", es: "Es mejor que te quedes.", tag: "impersonal + subjunctive" },
    { en: "I wish I spoke Spanish fluently.", es: "Ojalá hablara español con fluidez.", tag: "subjunctive · ojalá" },
    { en: "If only we had more time!", es: "¡Si tuviéramos más tiempo!", tag: "subjunctive · unreal" },
    { en: "The house that they bought is old.", es: "La casa que compraron es vieja.", tag: "relative · preterite" },
    { en: "I don't remember where I put it.", es: "No recuerdo dónde lo puse.", tag: "indirect question" },
    { en: "She doesn't let me go out at night.", es: "No me deja salir por la noche.", tag: "dejar + infinitive" },
    { en: "I'll help you carry those bags.", es: "Te ayudo a llevar esas bolsas.", tag: "ayudar a + inf" },
    { en: "We agreed to meet at eight.", es: "Quedamos en vernos a las ocho.", tag: "quedar en + inf" },
    { en: "He pretended not to hear.", es: "Fingió no oír.", tag: "fingir + infinitive" },
    { en: "I'm about to finish.", es: "Estoy a punto de terminar.", tag: "periphrastic future" },
    { en: "She had just left when I arrived.", es: "Acababa de salir cuando llegué.", tag: "acabar de + inf" },
    { en: "I don't feel like going out.", es: "No tengo ganas de salir.", tag: "tener ganas de" },
    { en: "It's worth reading this article.", es: "Vale la pena leer este artículo.", tag: "vale la pena" },
    { en: "I'd rather stay home.", es: "Prefiero quedarme en casa.", tag: "preferir + inf" },
    { en: "She seems tired to me.", es: "Me parece cansada.", tag: "parecer + adjective" },
    { en: "It seems that they won.", es: "Parece que ganaron.", tag: "parecer que" },
    { en: "I don't know him personally.", es: "No lo conozco personalmente.", tag: "adverb placement" },
    { en: "Sometimes I still make mistakes.", es: "A veces todavía cometo errores.", tag: "adverb order" },
    { en: "Never have I seen such a thing.", es: "Nunca he visto tal cosa.", tag: "negation · emphasis" },
    { en: "Hardly had we arrived when it started to rain.", es: "Apenas habíamos llegado cuando empezó a llover.", tag: "sequence · pluperfect" },
    { en: "The problem is that we don't have time.", es: "El problema es que no tenemos tiempo.", tag: "noun clause · indicative" },
    { en: "The idea is for everyone to participate.", es: "La idea es que todos participen.", tag: "subjunctive · purpose noun" },
    { en: "I'm looking for someone who speaks French.", es: "Busco a alguien que hable francés.", tag: "subjunctive · unknown antecedent" },
    { en: "I'm calling the woman who speaks French.", es: "Llamo a la mujer que habla francés.", tag: "indicative · known antecedent" },
    { en: "Unless you hurry, we'll miss the train.", es: "A menos que te des prisa, perderemos el tren.", tag: "subjunctive · unless" },
    { en: "In case it rains, take an umbrella.", es: "Por si llueve, lleva un paraguas.", tag: "por si + indicative" },
    { en: "I'll call you as soon as I arrive.", es: "Te llamo en cuanto llegue.", tag: "subjunctive · en cuanto" },
    { en: "No matter what you say, I won't change my mind.", es: "Digas lo que digas, no cambiaré de opinión.", tag: "subjunctive · concession" },
    { en: "Whoever finds the keys gets a reward.", es: "Quien encuentre las llaves recibirá una recompensa.", tag: "subjunctive · relative" },
    { en: "I don't know why he did that.", es: "No sé por qué hizo eso.", tag: "indirect question" },
    { en: "Tell me why you didn't come.", es: "Dime por qué no viniste.", tag: "question word + preposition" },
    { en: "That's the reason I left.", es: "Esa es la razón por la que me fui.", tag: "por la que" },
    { en: "The film we're talking about is long.", es: "La película de la que hablamos es larga.", tag: "de la que" },
    { en: "I need a pen to write with.", es: "Necesito un bolígrafo con el que escribir.", tag: "relative + infinitive" },
    { en: "There's a lot to explain.", es: "Hay mucho que explicar.", tag: "hay + relative" },
    { en: "It's easy for me to understand.", es: "Para mí es fácil entender.", tag: "impersonal structure" },
    { en: "Spanish is hard for me.", es: "El español me resulta difícil.", tag: "resultar + adjective" },
    { en: "She became a doctor.", es: "Se hizo médica.", tag: "hacerse + profession" },
    { en: "He got married last summer.", es: "Se casó el verano pasado.", tag: "reflexive · event" },
    { en: "We met at the conference.", es: "Nos conocimos en la conferencia.", tag: "reciprocal · preterite" },
    { en: "They introduced themselves politely.", es: "Se presentaron educadamente.", tag: "reflexive · adverb" },
    { en: "I realized I was wrong.", es: "Me di cuenta de que me equivocaba.", tag: "darse cuenta" },
    { en: "She decided to study abroad.", es: "Decidió estudiar en el extranjero.", tag: "decidir + inf" },
    { en: "He refused to answer.", es: "Se negó a responder.", tag: "negarse a" },
    { en: "I succeeded in passing the exam.", es: "Conseguí aprobar el examen.", tag: "conseguir + inf" },
    { en: "She failed to notice the sign.", es: "No se percató del letrero.", tag: "percatarse de" },
    { en: "We ran out of milk.", es: "Se nos acabó la leche.", tag: "acabarse · impersonal" },
    { en: "The lights went out suddenly.", es: "Las luces se apagaron de repente.", tag: "reflexive · change" },
    { en: "I'm getting nervous.", es: "Me estoy poniendo nervioso.", tag: "ponerse + adjective" },
    { en: "She fell asleep during the movie.", es: "Se durmió durante la película.", tag: "pronominal verb" },
    { en: "Wake up early tomorrow.", es: "Levántate temprano mañana.", tag: "command · reflexive" },
    { en: "Don't sit on that chair.", es: "No te sientes en esa silla.", tag: "negative command" },
    { en: "Let's not argue about it.", es: "No discutamos sobre eso.", tag: "negative nosotros command" },
    { en: "I'd have called you if I had known.", es: "Te habría llamado si lo hubiera sabido.", tag: "conditional perfect" },
    { en: "If I had studied, I would have passed.", es: "Si hubiera estudiado, habría aprobado.", tag: "past conditional" },
    { en: "Tickets are sold here.", es: "Aquí se venden entradas.", tag: "passive · se" },
    { en: "I dropped the glass.", es: "Se me cayó el vaso.", tag: "accidental · se" },
    { en: "The important thing is to practice.", es: "Lo importante es practicar.", tag: "neuter lo" },
    { en: "We're short on chairs.", es: "Nos faltan sillas.", tag: "faltar" },
    { en: "More patience is needed.", es: "Hace falta más paciencia.", tag: "hace falta" },
    { en: "It's enough to tell the truth.", es: "Basta con decir la verdad.", tag: "bastar + inf" },
    { en: "Whatever you say surprises me.", es: "Cualquier cosa que digas me sorprende.", tag: "subjunctive · relative" },
    { en: "I haven't finished yet.", es: "Aún no he terminado.", tag: "ya · aún" },
    { en: "I still don't know.", es: "Todavía no lo sé.", tag: "ya · aún" },
    { en: "I already knew.", es: "Ya lo sabía.", tag: "ya · aún" },
    { en: "Meanwhile, we'll wait.", es: "Mientras tanto, esperaremos.", tag: "discourse" },
    { en: "The more he talks, the less I trust him.", es: "Cuanto más habla, menos confío en él.", tag: "comparative" },
    { en: "Hardly anything happened.", es: "Apenas pasó nada.", tag: "negation" },
    { en: "Almost no one came.", es: "Casi no vino nadie.", tag: "negation" },
    { en: "I'll do it for you right away.", es: "Te lo hago ahora mismo.", tag: "clitics" },
    { en: "He spoke without thinking.", es: "Habló sin pensar.", tag: "sin + inf" },
    { en: "She left without saying anything.", es: "Se fue sin decir nada.", tag: "sin + inf" },
    { en: "After resting, I felt better.", es: "Después de descansar, me sentí mejor.", tag: "time · inf" },
    { en: "I'm glad to see you.", es: "Me alegro de verte.", tag: "alegrarse de" },
    { en: "I'm tired of waiting.", es: "Estoy cansado de esperar.", tag: "cansarse de" },
    { en: "I dream of traveling.", es: "Sueño con viajar.", tag: "soñar con" },
    { en: "I insist on leaving.", es: "Insisto en irme.", tag: "insistir en" },
    { en: "He depends on his parents.", es: "Depende de sus padres.", tag: "depender de" },
    { en: "They voted against the proposal.", es: "Votaron en contra de la propuesta.", tag: "prepositions" },
    { en: "I'm in favor of the plan.", es: "Estoy a favor del plan.", tag: "prepositions" },
    { en: "Behind the house there's a garden.", es: "Detrás de la casa hay un jardín.", tag: "place · hay" },
    { en: "Among everyone, she stood out.", es: "Entre todos, ella destacó.", tag: "entre" },
    { en: "Toward evening, it cooled off.", es: "Hacia el atardecer, refrescó.", tag: "time" },
    { en: "From now on, I'll be careful.", es: "De ahora en adelante, tendré cuidado.", tag: "time" },
    { en: "In my view, you're right.", es: "A mi juicio, tienes razón.", tag: "discourse" },
    { en: "Despite the cost, we bought it.", es: "A pesar del precio, lo compramos.", tag: "concession" },
    { en: "Because of you, we're late.", es: "Por tu culpa, llegamos tarde.", tag: "cause" },
    { en: "Thanks to you, we succeeded.", es: "Gracias a ti, lo conseguimos.", tag: "cause" },
    { en: "Instead of running, he walked.", es: "En lugar de correr, caminó.", tag: "en lugar de" },
    { en: "Besides working, he studies.", es: "Además de trabajar, estudia.", tag: "además de" },
    { en: "I prefer tea to coffee.", es: "Prefiero el té al café.", tag: "comparison" },
    { en: "Neither option is ideal.", es: "Ninguna opción es ideal.", tag: "negation" },
    { en: "Both answers are wrong.", es: "Ambas respuestas están mal.", tag: "agreement" },
    { en: "He neither eats nor sleeps well.", es: "Ni come ni duerme bien.", tag: "ni… ni" },
    { en: "Either we leave now or we miss the train.", es: "O salimos ahora o perdemos el tren.", tag: "o… o" },
    { en: "The more of us there are, the better.", es: "Cuantos más seamos, mejor.", tag: "comparative" },
    { en: "That's all I ask.", es: "Eso es todo lo que pido.", tag: "relative" },
    { en: "Nothing worries me more than that.", es: "Nada me preocupa más que eso.", tag: "negation" },
    { en: "Something tells me you're right.", es: "Algo me dice que tienes razón.", tag: "indicative clause" },
    { en: "No one said a word.", es: "Nadie dijo una palabra.", tag: "negation" },
    { en: "I saw him leave.", es: "Lo vi salir.", tag: "perception + inf" },
    { en: "I heard her sing.", es: "La oí cantar.", tag: "perception + inf" },
    { en: "Let them in.", es: "Que entren.", tag: "subjunctive · command" },
    { en: "Don't let them escape.", es: "No dejes que se escapen.", tag: "dejar que" },
    { en: "Make sure he arrives on time.", es: "Asegúrate de que llegue a tiempo.", tag: "subjunctive" },
    { en: "I don't mind waiting.", es: "No me importa esperar.", tag: "importar + inf" },
    { en: "It's time we left.", es: "Ya es hora de que nos vayamos.", tag: "es hora de que" },
    { en: "It's about time you called.", es: "Ya iba siendo hora de que llamaras.", tag: "subjunctive · time" },
    { en: "I suggest he rest.", es: "Sugiero que descanse.", tag: "subjunctive" },
    { en: "They ordered him to wait.", es: "Le ordenaron que esperara.", tag: "subjunctive · reported" },
    { en: "I'll wait until you tell me.", es: "Esperaré hasta que me lo digas.", tag: "hasta que" },
    { en: "He's happy with what he has.", es: "Está contento con lo que tiene.", tag: "lo que" },
    { en: "I'll go with whoever you choose.", es: "Iré con quien tú elijas.", tag: "subjunctive · relative" },
    { en: "I'll sit wherever there's space.", es: "Me sentaré donde haya sitio.", tag: "subjunctive · donde" },
    { en: "That's where I left it.", es: "Ahí es donde lo dejé.", tag: "emphatic structure" },
    { en: "That's why I didn't go.", es: "Por eso no fui.", tag: "por eso" },
    { en: "I called because we need help.", es: "Llamé porque necesitamos ayuda.", tag: "porque" },
    { en: "I don't know how he does it.", es: "No sé cómo lo hace.", tag: "indirect question" },
    { en: "Show me how you fixed it.", es: "Muéstrame cómo lo arreglaste.", tag: "cómo" },
    { en: "Tell me what happened.", es: "Cuéntame qué pasó.", tag: "questions" },
    { en: "I don't remember what you said.", es: "No recuerdo lo que dijiste.", tag: "lo que" },
    { en: "Despite his age, he's wise.", es: "A pesar de su edad, es sabio.", tag: "concession" },
    { en: "Given the risk, we stayed.", es: "Ante el riesgo, nos quedamos.", tag: "prepositions" },
    { en: "Considering the cost, it's cheap.", es: "Teniendo en cuenta el coste, es barato.", tag: "gerund" },
    { en: "Suppose it's true: then what?", es: "Supongamos que sea verdad: ¿entonces qué?", tag: "subjunctive" },
    { en: "Unless I'm wrong, you're right.", es: "Si no me equivoco, tienes razón.", tag: "condition" },
    { en: "If it rains, we'll stay home.", es: "Si llueve, nos quedaremos en casa.", tag: "conditional · si" },
    { en: "When it rains, I take the bus.", es: "Cuando llueve, cojo el autobús.", tag: "habitual · cuando" },
    { en: "Every time I hear that song, I smile.", es: "Cada vez que oigo esa canción, sonrío.", tag: "cada vez que" },
    { en: "The day we met, everything changed.", es: "El día que nos conocimos, todo cambió.", tag: "el día que" },
    { en: "I'll help you as long as you're honest.", es: "Te ayudaré mientras seas honesto.", tag: "mientras + subj" },
    { en: "He talks as if he knew everything.", es: "Habla como si lo supiera todo.", tag: "como si" },
    { en: "They acted as if nothing had happened.", es: "Actuaron como si no hubiera pasado nada.", tag: "como si" },
    { en: "I'd rather you didn't come.", es: "Preferiría que no vinieras.", tag: "subjunctive · preference" },
    { en: "I hope it doesn't rain.", es: "Espero que no llueva.", tag: "subjunctive · hope" },
    { en: "It's essential that we be on time.", es: "Es fundamental que seamos puntuales.", tag: "subjunctive" },
    { en: "It may be that he's right.", es: "Puede que tenga razón.", tag: "puede que" },
    { en: "Maybe they'll cancel the flight.", es: "Quizás cancelen el vuelo.", tag: "subjunctive" },
    { en: "Perhaps we're mistaken.", es: "Tal vez nos equivoquemos.", tag: "subjunctive" },
    { en: "You'd better leave now.", es: "Más vale que te vayas ya.", tag: "más vale que" },
    { en: "Be careful not to fall.", es: "Ten cuidado de no caerte.", tag: "command · reflexive" },
    { en: "Look how much you've grown!", es: "¡Mira cuánto has crecido!", tag: "exclamatory" },
    { en: "What a surprise!", es: "¡Qué sorpresa!", tag: "exclamatory" },
    { en: "How kind you are!", es: "¡Qué amable eres!", tag: "exclamatory" },
    { en: "Time flies.", es: "El tiempo vuela.", tag: "idiom" },
    { en: "I wish I were younger.", es: "Ojalá fuera más joven.", tag: "ojalá · imperfect subj" },
    { en: "If only we had known!", es: "¡Si lo hubiéramos sabido!", tag: "pluperfect subj" },
    { en: "Let him speak first.", es: "Que hable primero.", tag: "subjunctive · command" },
    { en: "May everything go well.", es: "Que todo salga bien.", tag: "subjunctive · wish" },
    { en: "Whoever wins must be fair.", es: "Quien gane tiene que ser justo.", tag: "subjunctive · relative" },
    { en: "Whatever you decide, I'll support you.", es: "Lo que decidas, te apoyaré.", tag: "lo que" },
    { en: "Wherever you are, call me.", es: "Donde estés, llámame.", tag: "donde + subj" },
    { en: "However you solve it, it's fine.", es: "Como lo resuelvas, está bien.", tag: "como + subj" },
    { en: "I barely had time to eat.", es: "Apenas tuve tiempo de comer.", tag: "apenas" },
    { en: "She can already read.", es: "Ya sabe leer.", tag: "saber + inf" },
    { en: "We're no longer friends.", es: "Ya no somos amigos.", tag: "ya no" },
    { en: "Not yet.", es: "Todavía no.", tag: "short answers" },
    { en: "Already?", es: "¿Ya?", tag: "questions" },
    { en: "It's been a while since we talked.", es: "Hace tiempo que no hablamos.", tag: "hace que" },
    { en: "It's been years since I saw her.", es: "Hace años que no la veo.", tag: "hace que" },
    { en: "I've been studying for hours.", es: "Llevo horas estudiando.", tag: "llevar + gerund" },
    { en: "It took me two days to finish it.", es: "Tardé dos días en terminarlo.", tag: "tardar en" },
    { en: "We're about to start.", es: "Estamos a punto de empezar.", tag: "estar a punto de" },
    { en: "He had just left when I arrived.", es: "Acababa de marcharse cuando llegué.", tag: "acabar de" },
    { en: "I'm dying to see the results.", es: "Me muero por ver los resultados.", tag: "morirse por" },
    { en: "I'd love to go with you.", es: "Me encantaría ir contigo.", tag: "conditional · polite" },
    { en: "It turns out I know him.", es: "Resulta que lo conozco.", tag: "resultar que" },
    { en: "Turning the corner, he saw the sea.", es: "Al girar la esquina, vio el mar.", tag: "al + inf" },
    { en: "Having read the letter, she cried.", es: "Habiendo leído la carta, lloró.", tag: "perfect participle" },
    { en: "If I were rich, I'd travel.", es: "Si fuera rico, viajaría.", tag: "conditional · imperfect subj" },
    { en: "Were it not for you, I would have failed.", es: "De no ser por ti, habría suspendido.", tag: "de no ser por" },
    { en: "Not even he believed it.", es: "Ni él lo creyó.", tag: "ni siquiera" },
    { en: "Scarcely had we begun when it ended.", es: "Apenas habíamos empezado cuando terminó.", tag: "pluperfect" },
    { en: "No sooner had I spoken than he agreed.", es: "Apenas había hablado cuando aceptó.", tag: "pluperfect" },
    { en: "He came so we could talk.", es: "Vino para que pudiéramos hablar.", tag: "para que" },
    { en: "She left without my seeing her.", es: "Se fue sin que yo la viera.", tag: "sin que" },
    { en: "I'm afraid of falling.", es: "Tengo miedo de caerme.", tag: "miedo de + inf" },
    { en: "I'm afraid of dogs.", es: "Le tengo miedo a los perros.", tag: "tener miedo a" },
    { en: "I trust you.", es: "Confío en ti.", tag: "confiar en" },
    { en: "It depends on you.", es: "Depende de ti.", tag: "depender de" },
    { en: "I'm counting on you.", es: "Cuento contigo.", tag: "contar con" },
    { en: "Believe me, it's true.", es: "Créeme, es verdad.", tag: "command · clitics" },
    { en: "Tell me the truth, I beg you.", es: "Dime la verdad, te lo ruego.", tag: "rogar" },
    { en: "I refuse to believe it.", es: "Me niego a creerlo.", tag: "negarse a" },
    { en: "He managed to escape.", es: "Logró escapar.", tag: "lograr + inf" },
    { en: "We failed to convince them.", es: "No logramos convencerlos.", tag: "lograr" },
    { en: "He learned to drive last year.", es: "Aprendió a conducir el año pasado.", tag: "aprender a" },
    { en: "Stop shouting!", es: "¡Deja de gritar!", tag: "dejar de" },
    { en: "Keep trying!", es: "¡Sigue intentándolo!", tag: "seguir + gerund" },
    { en: "Try not to be late.", es: "Procura no llegar tarde.", tag: "procurar + inf" },
    { en: "Car for sale.", es: "Se vende coche.", tag: "passive · se" },
    { en: "They say it's true.", es: "Dicen que es verdad.", tag: "reported speech" },
    { en: "It's said that he resigned.", es: "Se dice que dimitió.", tag: "impersonal · se" },
    { en: "People say she's brilliant.", es: "Dicen que es brillante.", tag: "reported speech" },
    { en: "I'm told you're leaving.", es: "Me han dicho que te vas.", tag: "reported speech" },
    { en: "I doubt we'll finish today.", es: "Dudo que terminemos hoy.", tag: "subjunctive · doubt" },
    { en: "I don't doubt we'll finish today.", es: "No dudo que terminaremos hoy.", tag: "indicative · no doubt" },
    { en: "It's true that he's ill.", es: "Es verdad que está enfermo.", tag: "indicative · fact" },
    { en: "It's unlikely that he'll come.", es: "Es poco probable que venga.", tag: "subjunctive" },
    { en: "It's possible that she's right.", es: "Es posible que tenga razón.", tag: "subjunctive" },
    { en: "I'm glad you came.", es: "Me alegra que hayas venido.", tag: "emotion + perfect subj" },
    { en: "Provided there's food, I'll stay.", es: "Con tal de que haya comida, me quedaré.", tag: "con tal de que" },
    { en: "I want them to leave.", es: "Quiero que se vayan.", tag: "subjunctive · desire" },
    { en: "They want me to speak.", es: "Quieren que hable.", tag: "subjunctive" },
    { en: "I forbid you to go.", es: "Te prohíbo que vayas.", tag: "subjunctive · prohibition" },
    { en: "He recommends that we wait.", es: "Nos recomienda que esperemos.", tag: "subjunctive" },
    { en: "It's annoying that they smoke here.", es: "Es molesto que fumen aquí.", tag: "subjunctive · judgment" },
    { en: "It's remarkable that she succeeded.", es: "Es notable que lo haya conseguido.", tag: "subjunctive" },
    { en: "I'm not convinced it's true.", es: "No estoy convencido de que sea verdad.", tag: "subjunctive" },
    { en: "It seems unlikely they'll agree.", es: "Parece poco probable que se pongan de acuerdo.", tag: "subjunctive" },
    { en: "It's a shame you missed it.", es: "Es una lástima que te lo hayas perdido.", tag: "subjunctive" },
    { en: "It's better that you not go alone.", es: "Es mejor que no vayas solo.", tag: "subjunctive" },
    { en: "I'm looking forward to seeing you.", es: "Estoy deseando verte.", tag: "estar deseando" },
    { en: "The minute he arrived, everyone clapped.", es: "En el momento en que llegó, todos aplaudieron.", tag: "time clause" },
    { en: "Whenever he calls, I'm busy.", es: "Siempre que llama, estoy ocupado.", tag: "siempre que · habitual" },
    { en: "Every time he spoke, people listened.", es: "Cada vez que hablaba, la gente escuchaba.", tag: "imperfect · habit" },
    { en: "I'll help you in exchange for honesty.", es: "Te ayudaré a cambio de tu honestidad.", tag: "a cambio de" },
    { en: "I'll exchange this for that.", es: "Cambiaré esto por aquello.", tag: "cambiar por" },
    { en: "She changed her mind.", es: "Cambió de idea.", tag: "reflexive idea" },
    { en: "He got angry at the news.", es: "Se enfadó con la noticia.", tag: "reflexive · emotion" },
    { en: "We got lost in the forest.", es: "Nos perdimos en el bosque.", tag: "reflexive" },
    { en: "They got married young.", es: "Se casaron jóvenes.", tag: "reflexive" },
    { en: "I got dressed quickly.", es: "Me vestí rápido.", tag: "reflexive · preterite" },
    { en: "She washed her hands.", es: "Se lavó las manos.", tag: "reflexive · body" },
    { en: "We brushed our teeth.", es: "Nos cepillamos los dientes.", tag: "reflexive · body" },
    { en: "He shaved this morning.", es: "Se afeitó esta mañana.", tag: "reflexive" },
    { en: "I don't deny that it's difficult.", es: "No niego que sea difícil.", tag: "subjunctive" },
    { en: "It's necessary for you to sign.", es: "Es necesario que firmes.", tag: "subjunctive" },
    { en: "It's impossible for him to come.", es: "Es imposible que venga.", tag: "subjunctive" },
    { en: "It's probable that they'll win.", es: "Es probable que ganen.", tag: "subjunctive" },
    { en: "I'm sad that you can't come.", es: "Me entristece que no puedas venir.", tag: "subjunctive · emotion" },
    { en: "I fear that we may be late.", es: "Temo que lleguemos tarde.", tag: "subjunctive · fear" },
    { en: "I'm sure that he'll come.", es: "Estoy seguro de que vendrá.", tag: "indicative · certainty" },
    { en: "She pretended not to see me.", es: "Fingió no verme.", tag: "fingir + inf" },
    { en: "He threatened to quit.", es: "Amenazó con dimitir.", tag: "amenazar con" },
    { en: "She promised to call.", es: "Prometió llamar.", tag: "prometer + inf" },
    { en: "They agreed to meet at eight.", es: "Quedaron en verse a las ocho.", tag: "quedar en" },
    { en: "I offered to help.", es: "Ofrecí ayudar.", tag: "ofrecer + inf" },
    { en: "He refused to answer.", es: "Se negó a contestar.", tag: "negarse a" },
    { en: "We decided to stay.", es: "Decidimos quedarnos.", tag: "decidir + inf" },
    { en: "She tried to open it.", es: "Intentó abrirlo.", tag: "intentar + clitic" },
    { en: "He began to understand.", es: "Empezó a entenderlo.", tag: "empezar a" },
    { en: "We continued walking.", es: "Seguimos caminando.", tag: "seguir + gerund" },
    { en: "She stopped smoking.", es: "Dejó de fumar.", tag: "dejar de" },
    { en: "He returned to work.", es: "Volvió a trabajar.", tag: "volver a" },
    { en: "I'll try again tomorrow.", es: "Lo intentaré otra vez mañana.", tag: "future" },
    { en: "You should have told me.", es: "Deberías habérmelo dicho.", tag: "deber + perfect inf" },
    { en: "You could have helped.", es: "Podrías haber ayudado.", tag: "perfect conditional" },
    { en: "She must have forgotten.", es: "Debe de haberlo olvidado.", tag: "probability · perfect" },
    { en: "They might have left already.", es: "Puede que ya se hayan ido.", tag: "perfect subjunctive" },
    { en: "I'd rather stay than go.", es: "Prefiero quedarme antes que irme.", tag: "antes que" },
    { en: "Rather than wait, we left.", es: "En vez de esperar, nos fuimos.", tag: "en vez de" },
    { en: "Besides being smart, she's kind.", es: "Además de ser lista, es amable.", tag: "además de + ser" },
    { en: "Without your help, we'd have lost.", es: "Sin tu ayuda, habríamos perdido.", tag: "condition" },
    { en: "With more time, we'd finish.", es: "Con más tiempo, terminaríamos.", tag: "conditional" },
    { en: "By studying daily, you'll improve.", es: "Estudiando a diario, mejorarás.", tag: "gerund · means" },
    { en: "To understand, you must listen.", es: "Para entender, hay que escuchar.", tag: "hay que" },
    { en: "It's hard to believe.", es: "Es difícil de creer.", tag: "de + inf" },
    { en: "It's the first time I've tried it.", es: "Es la primera vez que lo pruebo.", tag: "present · experience" },
    { en: "It was the last time I saw her.", es: "Fue la última vez que la vi.", tag: "preterite · relative" },
    { en: "The house needs painting.", es: "La casa necesita pintura.", tag: "necesitar + noun" },
    { en: "The house needs to be painted.", es: "La casa necesita que la pinten.", tag: "subjunctive · need" },
    { en: "I need you to listen.", es: "Necesito que escuches.", tag: "subjunctive" },
    { en: "There's nothing to fear.", es: "No hay nada que temer.", tag: "relative" },
    { en: "There's someone at the door.", es: "Hay alguien en la puerta.", tag: "hay" },
    { en: "There used to be a shop here.", es: "Aquí había una tienda.", tag: "imperfect · hay" },
    { en: "There will be a meeting tomorrow.", es: "Mañana habrá una reunión.", tag: "future · haber" },
    { en: "There might be traffic.", es: "Puede haber tráfico.", tag: "probability" },
    { en: "It's cold today.", es: "Hoy hace frío.", tag: "hacer · weather" },
    { en: "It's five o'clock.", es: "Son las cinco.", tag: "time · ser" },
    { en: "It's me.", es: "Soy yo.", tag: "identity" },
    { en: "It's them.", es: "Son ellos.", tag: "identity" },
    { en: "What is it about?", es: "¿De qué se trata?", tag: "tratarse de" },
    { en: "I'm not interested in that.", es: "Eso no me interesa.", tag: "interesar" },
    { en: "That matters to me a lot.", es: "Eso me importa mucho.", tag: "importar" },
    { en: "I'm afraid of them.", es: "Les tengo miedo.", tag: "tener miedo" },
    { en: "She's mad at me.", es: "Está enfadada conmigo.", tag: "estar + prep" },
    { en: "He's satisfied with the result.", es: "Está satisfecho con el resultado.", tag: "estar + adj" },
    { en: "We agree on that.", es: "Estamos de acuerdo en eso.", tag: "agreement phrase" },
    { en: "They disagree about politics.", es: "No están de acuerdo sobre la política.", tag: "negation" },
    { en: "I agree with you.", es: "Estoy de acuerdo contigo.", tag: "agreement" },
    { en: "She disagrees with him.", es: "Ella no está de acuerdo con él.", tag: "negation" },
    { en: "He works as a lawyer.", es: "Trabaja de abogado.", tag: "de + profession" },
    { en: "She's dressed as a nurse.", es: "Va vestida de enfermera.", tag: "ir + past participle" },
    { en: "They treat me like a child.", es: "Me tratan como a un niño.", tag: "como" },
    { en: "Use this as a model.", es: "Usa esto como modelo.", tag: "como" },
    { en: "I'll see you on Monday.", es: "Nos vemos el lunes.", tag: "time · article" },
    { en: "I'll see you in May.", es: "Nos vemos en mayo.", tag: "months" },
    { en: "See you in the summer.", es: "Nos vemos en verano.", tag: "seasons" },
    { en: "I'll call you at noon.", es: "Te llamo al mediodía.", tag: "time" },
    { en: "We arrived at midnight.", es: "Llegamos a medianoche.", tag: "time" },
    { en: "The store opens at nine.", es: "La tienda abre a las nueve.", tag: "time" },
    { en: "School starts in September.", es: "El curso empieza en septiembre.", tag: "months" },
    { en: "I've been here since Monday.", es: "Estoy aquí desde el lunes.", tag: "desde" },
    { en: "We'll stay until Friday.", es: "Nos quedaremos hasta el viernes.", tag: "hasta" },
    { en: "Between classes, I read.", es: "Entre clase y clase, leo.", tag: "entre" },
    { en: "Among friends, we relaxed.", es: "Entre amigos, nos relajamos.", tag: "entre" },
    { en: "Against all odds, we won.", es: "Contra todo pronóstico, ganamos.", tag: "idiom" },
    { en: "For all I know, he's gone.", es: "Por lo que yo sé, se ha ido.", tag: "discourse" },
    { en: "As far as I remember, it was blue.", es: "Hasta donde recuerdo, era azul.", tag: "discourse" },
    { en: "In case of fire, call emergency services.", es: "En caso de incendio, llama a emergencias.", tag: "en caso de" },
    { en: "In spite of everything, we're happy.", es: "A pesar de todo, somos felices.", tag: "concession" },
    { en: "Because of the noise, I couldn't sleep.", es: "Por el ruido, no pude dormir.", tag: "cause" },
    { en: "Owing to the delay, we missed it.", es: "Debido al retraso, lo perdimos.", tag: "debido a" },
    { en: "According to the rules, it's allowed.", es: "Según las normas, está permitido.", tag: "según" },
    { en: "Unlike you, I'm punctual.", es: "A diferencia de ti, soy puntual.", tag: "comparison" },
    { en: "Compared to last year, it's better.", es: "Comparado con el año pasado, es mejor.", tag: "comparado con" },
    { en: "Regarding your question, I'll answer later.", es: "En cuanto a tu pregunta, responderé más tarde.", tag: "en cuanto a" },
    { en: "As for me, I'm fine.", es: "Por mi parte, estoy bien.", tag: "discourse" },
    { en: "As for her, she disagrees.", es: "Por su parte, ella no está de acuerdo.", tag: "discourse" },
    { en: "In other words, we failed.", es: "En otras palabras, fracasamos.", tag: "discourse" },
    { en: "That is to say, it's complicated.", es: "Es decir, es complicado.", tag: "discourse" },
    { en: "For example, this case.", es: "Por ejemplo, este caso.", tag: "discourse" },
    { en: "In general, people are kind.", es: "En general, la gente es amable.", tag: "discourse" },
    { en: "At least we tried.", es: "Al menos lo intentamos.", tag: "discourse" },
    { en: "At most, it'll take an hour.", es: "Como mucho, tardará una hora.", tag: "discourse" },
    { en: "More or less, I understand.", es: "Más o menos, lo entiendo.", tag: "discourse" },
    { en: "Little by little, you'll improve.", es: "Poco a poco, mejorarás.", tag: "discourse" },
    { en: "From time to time, we meet.", es: "De vez en cuando, nos vemos.", tag: "frequency" },
    { en: "Once in a while, I travel.", es: "De cuando en cuando, viajo.", tag: "frequency" },
    { en: "Right away, he understood.", es: "En seguida, lo entendió.", tag: "time" },
    { en: "Sooner or later, we'll know.", es: "Tarde o temprano, lo sabremos.", tag: "idiom" },
    { en: "All of a sudden, it started to rain.", es: "De repente, empezó a llover.", tag: "de repente" },
    { en: "In the end, we agreed.", es: "Al final, llegamos a un acuerdo.", tag: "al final" },
    { en: "At first, I didn't like it.", es: "Al principio, no me gustó.", tag: "al principio" },
    { en: "In the meantime, read this.", es: "Mientras tanto, lee esto.", tag: "mientras tanto" },
    { en: "From then on, I was careful.", es: "A partir de entonces, tuve cuidado.", tag: "time" },
    { en: "Until then, wait.", es: "Hasta entonces, espera.", tag: "time" },
    { en: "Since then, nothing's been the same.", es: "Desde entonces, nada ha sido igual.", tag: "desde entonces" },
    { en: "By then, we'll be ready.", es: "Para entonces, estaremos listos.", tag: "para entonces" },
    { en: "Before long, it'll be winter.", es: "Dentro de poco, será invierno.", tag: "dentro de poco" },
    { en: "Long ago, this was a forest.", es: "Hace mucho, esto era un bosque.", tag: "hace mucho" },
    { en: "Not long ago, I moved.", es: "Hace poco, me mudé.", tag: "hace poco" },
    { en: "In two weeks, I'll return.", es: "Dentro de dos semanas, volveré.", tag: "future time" },
    { en: "Two weeks ago, I arrived.", es: "Hace dos semanas que llegué.", tag: "hace + time" },
    { en: "Within an hour, call me.", es: "Dentro de una hora, llámame.", tag: "dentro de" },
    { en: "For two hours, I waited.", es: "Durante dos horas, esperé.", tag: "durante" },
    { en: "Since last year, prices rose.", es: "Desde el año pasado, subieron los precios.", tag: "desde" },
    { en: "Until recently, I didn't know.", es: "Hasta hace poco, no lo sabía.", tag: "hasta" },
    { en: "As soon as possible, please.", es: "Lo antes posible, por favor.", tag: "idiom" },
    { en: "The sooner, the better.", es: "Cuanto antes, mejor.", tag: "comparative" },
    { en: "The later, the worse.", es: "Cuanto más tarde, peor.", tag: "comparative" },
    { en: "So much the better.", es: "Tanto mejor.", tag: "idiom" },
    { en: "So much the worse.", es: "Tanto peor.", tag: "idiom" },
    { en: "All the better if you come.", es: "Mejor aún si vienes.", tag: "idiom" },
    { en: "Even better, bring a friend.", es: "Mejor aún, trae a un amigo.", tag: "discourse" },
    { en: "Worse still, he lied.", es: "Peor aún, mintió.", tag: "discourse" },
    { en: "In any case, we'll see.", es: "En todo caso, ya veremos.", tag: "discourse" },
    { en: "At any rate, it's done.", es: "De todos modos, está hecho.", tag: "discourse" },
    { en: "Anyway, I don't care.", es: "En fin, no me importa.", tag: "discourse" },
    { en: "To sum up, we agree.", es: "En resumen, estamos de acuerdo.", tag: "discourse" },
    { en: "In short, it's impossible.", es: "En resumidas cuentas, es imposible.", tag: "discourse" },
    { en: "On the one hand, it's cheap.", es: "Por un lado, es barato.", tag: "discourse" },
    { en: "On the other hand, it's slow.", es: "Por otro lado, es lento.", tag: "discourse" },
    { en: "On the contrary, I liked it.", es: "Al contrario, me gustó.", tag: "discourse" },
    { en: "Instead, we stayed home.", es: "En cambio, nos quedamos en casa.", tag: "discourse" },
    { en: "Nevertheless, we continued.", es: "No obstante, seguimos.", tag: "discourse" },
    { en: "Still, I have doubts.", es: "Aun así, tengo dudas.", tag: "discourse" },
    { en: "Therefore, we must act.", es: "Por tanto, debemos actuar.", tag: "discourse" },
    { en: "Thus, the problem was solved.", es: "Así pues, se resolvió el problema.", tag: "discourse" },
    { en: "Hence, we conclude.", es: "Por consiguiente, concluimos.", tag: "discourse" },
    { en: "Consequently, he resigned.", es: "En consecuencia, dimitió.", tag: "discourse" },
    { en: "As a result, we won.", es: "Como resultado, ganamos.", tag: "discourse" },
    { en: "After all, he's only a child.", es: "Al fin y al cabo, solo es un niño.", tag: "idiom" },
    { en: "At last, we arrived.", es: "Por fin, llegamos.", tag: "por fin" },
    { en: "Finally, she agreed.", es: "Finalmente, aceptó.", tag: "finally" },
    { en: "Ultimately, it's your choice.", es: "Al cabo, es tu decisión.", tag: "discourse" },
    { en: "First of all, listen.", es: "Ante todo, escucha.", tag: "discourse" },
    { en: "Above all, be honest.", es: "Sobre todo, sé honesto.", tag: "discourse" },
    { en: "Besides, it's cheap.", es: "Además, es barato.", tag: "además" },
    { en: "Moreover, it's fast.", es: "Es más, es rápido.", tag: "discourse" },
    { en: "Furthermore, it's safe.", es: "Encima, es seguro.", tag: "discourse" },
  ];

  const seen = new Set();
  window.SENTENCE_BANK = window.SENTENCE_BANK.filter((row) => {
    const k = String(row.es ?? "")
      .trim()
      .toLowerCase();
    if (!k || seen.has(k)) return false;
    seen.add(k);
    return true;
  });
})();
