/* global window */
(() => {
  "use strict";

  /**
   * Word object shape:
   * { es: string, en: string, tag?: string }
   *
   * Keep this list large and practical. You can add more inside the app too.
   */
  window.WORD_BANK = [
    // Core / greetings
    { es: "hola", en: "hello", tag: "basics" },
    { es: "adiós", en: "goodbye", tag: "basics" },
    { es: "por favor", en: "please", tag: "basics" },
    { es: "gracias", en: "thank you", tag: "basics" },
    { es: "de nada", en: "you're welcome", tag: "basics" },
    { es: "perdón", en: "sorry / excuse me", tag: "basics" },
    { es: "lo siento", en: "I'm sorry", tag: "basics" },
    { es: "buenos días", en: "good morning", tag: "basics" },
    { es: "buenas tardes", en: "good afternoon", tag: "basics" },
    { es: "buenas noches", en: "good night", tag: "basics" },
    { es: "¿qué tal?", en: "how's it going?", tag: "basics" },
    { es: "¿cómo estás?", en: "how are you?", tag: "basics" },
    { es: "bien", en: "well / fine", tag: "basics" },
    { es: "mal", en: "badly", tag: "basics" },
    { es: "más o menos", en: "so-so", tag: "basics" },
    { es: "¿cómo te llamas?", en: "what's your name?", tag: "basics" },
    { es: "me llamo…", en: "my name is…", tag: "basics" },
    { es: "mucho gusto", en: "nice to meet you", tag: "basics" },
    { es: "encantado/a", en: "pleased to meet you", tag: "basics" },
    { es: "¿de dónde eres?", en: "where are you from?", tag: "basics" },
    { es: "soy de…", en: "I'm from…", tag: "basics" },
    { es: "sí", en: "yes", tag: "basics" },
    { es: "no", en: "no", tag: "basics" },
    { es: "tal vez", en: "possibly", tag: "basics" },
    { es: "claro", en: "of course", tag: "basics" },
    { es: "vale", en: "okay / alright", tag: "basics" },
    { es: "bienvenido/a", en: "welcome", tag: "basics" },
    { es: "salud", en: "bless you", tag: "basics" },

    // Numbers / time
    { es: "uno", en: "one", tag: "numbers" },
    { es: "dos", en: "two", tag: "numbers" },
    { es: "tres", en: "three", tag: "numbers" },
    { es: "cuatro", en: "four", tag: "numbers" },
    { es: "cinco", en: "five", tag: "numbers" },
    { es: "seis", en: "six", tag: "numbers" },
    { es: "siete", en: "seven", tag: "numbers" },
    { es: "ocho", en: "eight", tag: "numbers" },
    { es: "nueve", en: "nine", tag: "numbers" },
    { es: "diez", en: "ten", tag: "numbers" },
    { es: "hoy", en: "today", tag: "time" },
    { es: "mañana", en: "tomorrow", tag: "time" },
    { es: "ayer", en: "yesterday", tag: "time" },
    { es: "ahora", en: "now", tag: "time" },
    { es: "luego", en: "later", tag: "time" },
    { es: "antes", en: "before", tag: "time" },
    { es: "después", en: "after", tag: "time" },
    { es: "siempre", en: "always", tag: "time" },
    { es: "nunca", en: "never", tag: "time" },
    { es: "a veces", en: "sometimes", tag: "time" },
    { es: "temprano", en: "early", tag: "time" },
    { es: "tarde", en: "late", tag: "time" },

    // People / pronouns
    { es: "yo", en: "I", tag: "people" },
    { es: "tú", en: "you (informal)", tag: "people" },
    { es: "usted", en: "you (formal)", tag: "people" },
    { es: "él", en: "he", tag: "people" },
    { es: "ella", en: "she", tag: "people" },
    { es: "nosotros", en: "we", tag: "people" },
    { es: "nosotras", en: "we (feminine)", tag: "people" },
    { es: "ellos", en: "they (masculine)", tag: "people" },
    { es: "ellas", en: "they (feminine)", tag: "people" },
    { es: "mi", en: "my", tag: "people" },
    { es: "tu", en: "your (informal)", tag: "people" },
    { es: "su", en: "his/her/your/their", tag: "people" },

    // Common verbs (infinitives)
    { es: "ser", en: "to be (permanent)", tag: "verbs" },
    { es: "estar", en: "to be (temporary)", tag: "verbs" },
    { es: "tener", en: "to have", tag: "verbs" },
    { es: "hacer", en: "to do / to make", tag: "verbs" },
    { es: "ir", en: "to go", tag: "verbs" },
    { es: "venir", en: "to come", tag: "verbs" },
    { es: "ver", en: "to see", tag: "verbs" },
    { es: "mirar", en: "to look at / watch", tag: "verbs" },
    { es: "oír", en: "to hear", tag: "verbs" },
    { es: "escuchar", en: "to listen", tag: "verbs" },
    { es: "hablar", en: "to speak", tag: "verbs" },
    { es: "decir", en: "to say / to tell", tag: "verbs" },
    { es: "preguntar", en: "to ask", tag: "verbs" },
    { es: "responder", en: "to answer", tag: "verbs" },
    { es: "poder", en: "to be able to / can", tag: "verbs" },
    { es: "querer", en: "to want / to love", tag: "verbs" },
    { es: "necesitar", en: "to need", tag: "verbs" },
    { es: "gustar", en: "to like", tag: "verbs" },
    { es: "amar", en: "to love", tag: "verbs" },
    { es: "comer", en: "to eat", tag: "verbs" },
    { es: "beber", en: "to drink", tag: "verbs" },
    { es: "vivir", en: "to live", tag: "verbs" },
    { es: "trabajar", en: "to work", tag: "verbs" },
    { es: "estudiar", en: "to study", tag: "verbs" },
    { es: "leer", en: "to read", tag: "verbs" },
    { es: "escribir", en: "to write", tag: "verbs" },
    { es: "aprender", en: "to learn", tag: "verbs" },
    { es: "enseñar", en: "to teach", tag: "verbs" },
    { es: "comprar", en: "to buy", tag: "verbs" },
    { es: "vender", en: "to sell", tag: "verbs" },
    { es: "pagar", en: "to pay", tag: "verbs" },
    { es: "abrir", en: "to open", tag: "verbs" },
    { es: "cerrar", en: "to close", tag: "verbs" },
    { es: "empezar", en: "to start", tag: "verbs" },
    { es: "terminar", en: "to finish", tag: "verbs" },
    { es: "llevar", en: "to carry / to wear", tag: "verbs" },
    { es: "poner", en: "to put / to place", tag: "verbs" },
    { es: "dar", en: "to give", tag: "verbs" },
    { es: "tomar", en: "to take / to drink", tag: "verbs" },
    { es: "usar", en: "to use", tag: "verbs" },
    { es: "ayudar", en: "to help", tag: "verbs" },
    { es: "buscar", en: "to look for", tag: "verbs" },
    { es: "encontrar", en: "to find", tag: "verbs" },
    { es: "esperar", en: "to wait / to hope", tag: "verbs" },
    { es: "llamar", en: "to call", tag: "verbs" },
    { es: "llegar", en: "to arrive", tag: "verbs" },
    { es: "salir", en: "to go out", tag: "verbs" },
    { es: "entrar", en: "to enter", tag: "verbs" },
    { es: "volver", en: "to return", tag: "verbs" },
    { es: "viajar", en: "to travel", tag: "verbs" },
    { es: "conocer", en: "to know (a person)", tag: "verbs" },
    { es: "saber", en: "to know (a fact)", tag: "verbs" },
    { es: "pensar", en: "to think", tag: "verbs" },
    { es: "creer", en: "to believe", tag: "verbs" },
    { es: "sentir", en: "to feel", tag: "verbs" },
    { es: "dormir", en: "to sleep", tag: "verbs" },

    // Travel / directions
    { es: "aquí", en: "here", tag: "travel" },
    { es: "allí", en: "there (far)", tag: "travel" },
    { es: "izquierda", en: "left", tag: "travel" },
    { es: "derecha", en: "right (direction)", tag: "travel" },
    { es: "recto", en: "straight", tag: "travel" },
    { es: "cerca", en: "near", tag: "travel" },
    { es: "lejos", en: "far", tag: "travel" },
    { es: "mapa", en: "map", tag: "travel" },
    { es: "calle", en: "street", tag: "travel" },
    { es: "ciudad", en: "city", tag: "travel" },
    { es: "país", en: "country", tag: "travel" },
    { es: "aeropuerto", en: "airport", tag: "travel" },
    { es: "boleto", en: "ticket", tag: "travel" },
    { es: "pasaporte", en: "passport", tag: "travel" },
    { es: "hotel", en: "hotel", tag: "travel" },
    { es: "habitación", en: "room", tag: "travel" },
    { es: "reserva", en: "reservation", tag: "travel" },

    // Food
    { es: "agua", en: "water", tag: "food" },
    { es: "café", en: "coffee", tag: "food" },
    { es: "té", en: "tea", tag: "food" },
    { es: "leche", en: "milk", tag: "food" },
    { es: "pan", en: "bread", tag: "food" },
    { es: "arroz", en: "rice", tag: "food" },
    { es: "pollo", en: "chicken", tag: "food" },
    { es: "carne", en: "meat", tag: "food" },
    { es: "pescado", en: "fish (food)", tag: "food" },
    { es: "verduras", en: "vegetables", tag: "food" },
    { es: "fruta", en: "fruit", tag: "food" },
    { es: "manzana", en: "apple", tag: "food" },
    { es: "plátano", en: "banana", tag: "food" },
    { es: "naranja", en: "orange", tag: "food" },
    { es: "queso", en: "cheese", tag: "food" },
    { es: "huevo", en: "egg", tag: "food" },
    { es: "azúcar", en: "sugar", tag: "food" },
    { es: "sal", en: "salt", tag: "food" },
    { es: "pimienta", en: "pepper", tag: "food" },
    { es: "aceite", en: "oil", tag: "food" },
    { es: "vinagre", en: "vinegar", tag: "food" },

    // Home
    { es: "casa", en: "house", tag: "home" },
    { es: "apartamento", en: "apartment", tag: "home" },
    { es: "puerta", en: "door", tag: "home" },
    { es: "ventana", en: "window", tag: "home" },
    { es: "cocina", en: "kitchen", tag: "home" },
    { es: "baño", en: "bathroom", tag: "home" },
    { es: "dormitorio", en: "bedroom", tag: "home" },
    { es: "sala", en: "living room", tag: "home" },
    { es: "mesa", en: "table", tag: "home" },
    { es: "silla", en: "chair", tag: "home" },
    { es: "cama", en: "bed", tag: "home" },
    { es: "llave", en: "key", tag: "home" },

    // Adjectives
    { es: "bueno", en: "good", tag: "adjectives" },
    { es: "malo", en: "bad", tag: "adjectives" },
    { es: "grande", en: "big", tag: "adjectives" },
    { es: "pequeño", en: "small", tag: "adjectives" },
    { es: "nuevo", en: "new", tag: "adjectives" },
    { es: "viejo", en: "old", tag: "adjectives" },
    { es: "bonito", en: "pretty", tag: "adjectives" },
    { es: "feo", en: "ugly", tag: "adjectives" },
    { es: "fácil", en: "easy", tag: "adjectives" },
    { es: "difícil", en: "difficult", tag: "adjectives" },
    { es: "rápido", en: "fast", tag: "adjectives" },
    { es: "lento", en: "slow", tag: "adjectives" },
    { es: "caro", en: "expensive", tag: "adjectives" },
    { es: "barato", en: "cheap", tag: "adjectives" },

    // Connectors / useful words
    { es: "y", en: "and", tag: "basics" },
    { es: "o", en: "or", tag: "basics" },
    { es: "pero", en: "but", tag: "basics" },
    { es: "porque", en: "because", tag: "basics" },
    { es: "para", en: "for / in order to", tag: "basics" },
    { es: "con", en: "with", tag: "basics" },
    { es: "sin", en: "without", tag: "basics" },
    { es: "muy", en: "very", tag: "basics" },
    { es: "también", en: "also", tag: "basics" },
    { es: "solo", en: "only / alone", tag: "basics" },
    { es: "todavía", en: "still", tag: "basics" },
    { es: "ya", en: "already / now", tag: "basics" },

    // Expand quickly with a practical starter bank (~250+ items)
    // Body
    { es: "cabeza", en: "head", tag: "body" },
    { es: "cara", en: "face", tag: "body" },
    { es: "ojo", en: "eye", tag: "body" },
    { es: "nariz", en: "nose", tag: "body" },
    { es: "boca", en: "mouth", tag: "body" },
    { es: "mano", en: "hand", tag: "body" },
    { es: "brazo", en: "arm", tag: "body" },
    { es: "pierna", en: "leg", tag: "body" },
    { es: "pie", en: "foot", tag: "body" },
    { es: "corazón", en: "heart", tag: "body" },

    // Weather
    { es: "tiempo", en: "weather / time", tag: "weather" },
    { es: "sol", en: "sun", tag: "weather" },
    { es: "lluvia", en: "rain", tag: "weather" },
    { es: "viento", en: "wind", tag: "weather" },
    { es: "nieve", en: "snow", tag: "weather" },
    { es: "calor", en: "heat", tag: "weather" },
    { es: "frío", en: "cold", tag: "weather" },

    // Work / school
    { es: "trabajo", en: "job / work", tag: "work" },
    { es: "oficina", en: "office", tag: "work" },
    { es: "reunión", en: "meeting", tag: "work" },
    { es: "correo", en: "mail / email", tag: "work" },
    { es: "escuela", en: "school", tag: "school" },
    { es: "clase", en: "class", tag: "school" },
    { es: "tarea", en: "homework", tag: "school" },
    { es: "examen", en: "exam", tag: "school" },

    // More everyday nouns
    { es: "amigo", en: "friend", tag: "people" },
    { es: "familia", en: "family", tag: "people" },
    { es: "niño", en: "boy / child", tag: "people" },
    { es: "niña", en: "girl / child", tag: "people" },
    { es: "hombre", en: "man", tag: "people" },
    { es: "mujer", en: "woman", tag: "people" },
    { es: "persona", en: "person", tag: "people" },
    { es: "nombre", en: "name", tag: "basics" },
    { es: "palabra", en: "word", tag: "basics" },
    { es: "pregunta", en: "question", tag: "basics" },
    { es: "respuesta", en: "answer", tag: "basics" },
    { es: "problema", en: "problem", tag: "basics" },
    { es: "idea", en: "idea", tag: "basics" },

    // Transport
    { es: "coche", en: "car", tag: "travel" },
    { es: "autobús", en: "bus", tag: "travel" },
    { es: "tren", en: "train", tag: "travel" },
    { es: "metro", en: "subway", tag: "travel" },
    { es: "bicicleta", en: "bicycle", tag: "travel" },

    // Clothes
    { es: "ropa", en: "clothes", tag: "clothes" },
    { es: "camisa", en: "shirt", tag: "clothes" },
    { es: "pantalones", en: "pants", tag: "clothes" },
    { es: "zapatos", en: "shoes", tag: "clothes" },
    { es: "chaqueta", en: "jacket", tag: "clothes" },

    // Tech
    { es: "teléfono", en: "phone", tag: "tech" },
    { es: "computadora", en: "computer", tag: "tech" },
    { es: "internet", en: "internet", tag: "tech" },
    { es: "contraseña", en: "password", tag: "tech" },

    // A big chunk of high-frequency words (curated, compact)
    { es: "hoy", en: "today", tag: "time" },
    { es: "mañana (la mañana)", en: "morning", tag: "time" },
    { es: "noche", en: "night", tag: "time" },
    { es: "semana", en: "week", tag: "time" },
    { es: "mes", en: "month", tag: "time" },
    { es: "año", en: "year", tag: "time" },
    { es: "hora", en: "hour", tag: "time" },
    { es: "minuto", en: "minute", tag: "time" },

    { es: "uno (una)", en: "one or a", tag: "basics" },
    { es: "este", en: "this", tag: "basics" },
    { es: "ese", en: "that", tag: "basics" },
    { es: "aquel", en: "that (far away)", tag: "basics" },
    { es: "aquí", en: "here", tag: "basics" },
    { es: "ahí", en: "there (near)", tag: "basics" },

    // (More will be appended programmatically below)
  ];

  // Add lots of additional everyday vocabulary without bloating manual edits.
  // This keeps the file readable while still giving you a big bank.
  const extra = [
    // Home + objects
    ["cuchara", "spoon", "home"],
    ["tenedor", "fork", "home"],
    ["cuchillo", "knife", "home"],
    ["plato", "plate", "home"],
    ["vaso", "glass", "home"],
    ["taza", "cup", "home"],
    ["botella", "bottle", "home"],
    ["toalla", "towel", "home"],
    ["jabón", "soap", "home"],
    ["ducha", "shower", "home"],
    ["espejo", "mirror", "home"],
    ["refrigerador", "fridge", "home"],
    ["horno", "oven", "home"],
    ["estufa", "stove", "home"],
    ["cortina", "curtain", "home"],
    ["pared", "wall", "home"],
    ["suelo", "floor", "home"],
    ["techo", "ceiling", "home"],

    // Food / restaurant
    ["desayuno", "breakfast", "food"],
    ["almuerzo", "lunch", "food"],
    ["cena", "dinner", "food"],
    ["restaurante", "restaurant", "food"],
    ["menú", "menu", "food"],
    ["cuenta", "bill / check", "food"],
    ["propina", "tip", "food"],
    ["hambre", "hunger", "food"],
    ["sed", "thirst", "food"],

    // Travel
    ["estación", "station", "travel"],
    ["parada", "stop", "travel"],
    ["taxi", "taxi", "travel"],
    ["billete", "banknote", "travel"],
    ["maleta", "suitcase", "travel"],
    ["equipaje", "luggage", "travel"],
    ["aduana", "customs", "travel"],

    // Feelings
    ["feliz", "happy", "feelings"],
    ["triste", "sad", "feelings"],
    ["cansado", "tired", "feelings"],
    ["enfermo", "sick", "feelings"],
    ["ocupado", "busy", "feelings"],
    ["nervioso", "nervous", "feelings"],
    ["emocionado", "excited", "feelings"],

    // Common phrases
    ["no entiendo", "I don't understand", "phrases"],
    ["no sé", "I don't know", "phrases"],
    ["¿puedes repetir?", "can you repeat?", "phrases"],
    ["más despacio", "more slowly", "phrases"],
    ["¿qué significa…?", "what does … mean?", "phrases"],
    ["¿dónde está…?", "where is …?", "phrases"],
    ["¿cuánto cuesta?", "how much does it cost?", "phrases"],
    ["¿qué hora es?", "what time is it?", "phrases"],
    ["tengo hambre", "I'm hungry", "phrases"],
    ["tengo sed", "I'm thirsty", "phrases"],

    // More high-frequency nouns (everyday)
    ["tienda", "store", "everyday"],
    ["mercado", "market", "everyday"],
    ["banco", "bank", "everyday"],
    ["hospital", "hospital", "everyday"],
    ["farmacia", "pharmacy", "everyday"],
    ["iglesia", "church", "everyday"],
    ["parque", "park", "everyday"],
    ["playa", "beach", "everyday"],
    ["montaña", "mountain", "everyday"],
    ["río", "river", "everyday"],
    ["mar", "sea", "everyday"],
    ["lago", "lake", "everyday"],
    ["bosque", "forest", "everyday"],
    ["árbol", "tree", "everyday"],
    ["flor", "flower", "everyday"],
    ["perro", "dog", "everyday"],
    ["gato", "cat", "everyday"],
    ["pájaro", "bird", "everyday"],
    ["caballo", "horse", "everyday"],
    ["pez", "fish (alive)", "everyday"],
    ["calle", "street", "everyday"],
    ["carretera", "road", "everyday"],
    ["puente", "bridge", "everyday"],
    ["plaza", "square", "everyday"],

    // Shopping / money
    ["dinero", "money", "shopping"],
    ["precio", "price", "shopping"],
    ["oferta", "sale / offer", "shopping"],
    ["descuento", "discount", "shopping"],
    ["tarjeta", "card", "shopping"],
    ["efectivo", "cash", "shopping"],
    ["cambio", "change", "shopping"],
    ["recibo", "receipt", "shopping"],

    // Health
    ["médico", "doctor", "health"],
    ["enfermera", "nurse", "health"],
    ["medicina", "medicine", "health"],
    ["dolor", "pain", "health"],
    ["fiebre", "fever", "health"],
    ["tos", "cough", "health"],
    ["alergia", "allergy", "health"],

    // Common adjectives (more)
    ["importante", "important", "adjectives"],
    ["interesante", "interesting", "adjectives"],
    ["aburrido", "boring", "adjectives"],
    ["fuerte", "strong", "adjectives"],
    ["débil", "weak", "adjectives"],
    ["limpio", "clean", "adjectives"],
    ["sucio", "dirty", "adjectives"],
    ["lleno", "full", "adjectives"],
    ["vacío", "empty", "adjectives"],
    ["correcto", "correct", "adjectives"],
    ["equivocado", "wrong", "adjectives"],
    ["abierto", "open", "adjectives"],
    ["cerrado", "closed", "adjectives"],
    ["seguro", "safe / sure", "adjectives"],
    ["peligroso", "dangerous", "adjectives"],

    // Common verbs (more)
    ["caminar", "to walk", "verbs"],
    ["correr", "to run", "verbs"],
    ["conducir", "to drive", "verbs"],
    ["cocinar", "to cook", "verbs"],
    ["llover", "to rain", "verbs"],
    ["llorar", "to cry", "verbs"],
    ["reír", "to laugh", "verbs"],
    ["pagar", "to pay", "verbs"],
    ["ganar", "to win / earn", "verbs"],
    ["perder", "to lose", "verbs"],
    ["dejar", "to let", "verbs"],
    ["intentar", "to try", "verbs"],
    ["explicar", "to explain", "verbs"],
    ["recordar", "to remember", "verbs"],
    ["olvidar", "to forget", "verbs"],
    ["cambiar", "to change", "verbs"],
    ["mejorar", "to improve", "verbs"],
    ["decidir", "to decide", "verbs"],
    ["elegir", "to choose", "verbs"],

    // More useful phrases
    ["¿puedes ayudarme?", "can you help me?", "phrases"],
    ["¿hablas inglés?", "do you speak English?", "phrases"],
    ["hablo un poco de español", "I speak a little Spanish", "phrases"],
    ["no hay problema", "no problem", "phrases"],
    ["¡qué suerte!", "how lucky!", "phrases"],
    ["¡qué pena!", "what a shame!", "phrases"],
    ["hasta luego", "see you later", "phrases"],
    ["hasta mañana", "see you tomorrow", "phrases"],
    ["buen viaje", "have a good trip", "phrases"],
  ];

  for (const [es, en, tag] of extra) window.WORD_BANK.push({ es, en, tag });

  const moreBulk = [
    // Clothing & colors
    ["abrigo", "coat", "clothes"],
    ["sombrero", "hat", "clothes"],
    ["gorra", "cap", "clothes"],
    ["calcetines", "socks", "clothes"],
    ["falda", "skirt", "clothes"],
    ["vestido", "dress", "clothes"],
    ["traje", "suit", "clothes"],
    ["jersey", "sweater / jersey", "clothes"],
    ["bufanda", "scarf", "clothes"],
    ["guantes", "gloves", "clothes"],
    ["blanco", "white", "colors"],
    ["negro", "black", "colors"],
    ["rojo", "red", "colors"],
    ["azul", "blue", "colors"],
    ["verde", "green", "colors"],
    ["amarillo", "yellow", "colors"],
    ["naranja", "orange", "colors"],
    ["morado", "purple", "colors"],
    ["rosa", "pink", "colors"],
    ["marrón", "brown", "colors"],
    ["gris", "gray", "colors"],
    // Food (more)
    ["sopa", "soup", "food"],
    ["ensalada", "salad", "food"],
    ["pasta", "pasta", "food"],
    ["pizza", "pizza", "food"],
    ["helado", "ice cream", "food"],
    ["mantequilla", "butter", "food"],
    ["miel", "honey", "food"],
    ["mermelada", "jam", "food"],
    ["salsa", "sauce", "food"],
    ["pimientos", "bell peppers", "food"],
    ["patata", "potato", "food"],
    ["tomate", "tomato", "food"],
    ["cebolla", "onion", "food"],
    ["ajo", "garlic", "food"],
    ["limón", "lemon", "food"],
    ["limonada", "lemonade", "food"],
    ["vino", "wine", "food"],
    ["cerveza", "beer", "food"],
    ["jugo", "juice", "food"],
    // Home (more)
    ["sofa", "sofa / couch", "home"],
    ["alfombra", "rug / carpet", "home"],
    ["lámpara", "lamp", "home"],
    ["enchufe", "outlet / plug", "home"],
    ["basura", "garbage / trash", "home"],
    ["escoba", "broom", "home"],
    ["detergente", "detergent", "home"],
    ["edificio", "building", "everyday"],
    ["ascensor", "elevator", "everyday"],
    ["escaleras", "stairs", "everyday"],
    // Sports & leisure
    ["fútbol", "soccer / football", "sports"],
    ["baloncesto", "basketball", "sports"],
    ["tenis", "tennis", "sports"],
    ["natación", "swimming", "sports"],
    ["bicicleta", "bicycle", "sports"],
    ["gimnasio", "gym", "sports"],
    ["partido", "match / game", "sports"],
    ["equipo", "team", "sports"],
    ["victoria", "victory", "sports"],
    ["ejercicio", "exercise", "sports"],
    // Nature / animals
    ["vaca", "cow", "animals"],
    ["cerdo", "pig", "animals"],
    ["oveja", "sheep", "animals"],
    ["rata", "rat", "animals"],
    ["serpiente", "snake", "animals"],
    ["insecto", "insect", "animals"],
    ["mariposa", "butterfly", "animals"],
    ["luna", "moon", "nature"],
    ["estrella", "star", "nature"],
    ["cielo", "sky", "nature"],
    ["nube", "cloud", "nature"],
    ["trueno", "thunder", "nature"],
    ["relámpago", "lightning", "nature"],
    ["terremoto", "earthquake", "nature"],
    // Professions
    ["ingeniero", "engineer", "work"],
    ["abogado", "lawyer", "work"],
    ["cocinero", "cook / chef", "work"],
    ["conductor", "driver", "work"],
    ["vendedor", "salesperson", "work"],
    ["cajero", "cashier", "work"],
    ["jefe", "boss", "work"],
    ["empleado", "employee", "work"],
    ["sueldo", "salary / wage", "work"],
    ["horario", "schedule", "work"],
    // Verbs / daily
    ["despertarse", "to wake up", "verbs"],
    ["vestirse", "to get dressed", "verbs"],
    ["ducharse", "to shower", "verbs"],
    ["desayunar", "to have breakfast", "verbs"],
    ["almorzar", "to have lunch", "verbs"],
    ["cenar", "to have dinner", "verbs"],
    ["subir", "to go up / to upload", "verbs"],
    ["bajar", "to go down / to lower", "verbs"],
    ["cruzar", "to cross", "verbs"],
    ["fumar", "to smoke", "verbs"],
    ["sufrir", "to suffer", "verbs"],
    ["soñar", "to dream", "verbs"],
    ["acostarse", "to go to bed / to lie down", "verbs"],
    ["llenar", "to fill", "verbs"],
    ["vaciar", "to empty", "verbs"],
    ["romper", "to break", "verbs"],
    ["arreglar", "to fix / to arrange", "verbs"],
    ["construir", "to build", "verbs"],
    ["votar", "to vote", "verbs"],
    ["proteger", "to protect", "verbs"],
    // Emotions / social
    ["enojado", "angry", "feelings"],
    ["asustado", "scared", "feelings"],
    ["avergonzado", "embarrassed", "feelings"],
    ["orgulloso", "proud", "feelings"],
    ["preocupado", "worried", "feelings"],
    ["tranquilo", "calm / relaxed", "feelings"],
    ["sorpresa", "surprise", "feelings"],
    ["abrazo", "hug", "people"],
    ["beso", "kiss", "people"],
    ["regalo", "gift", "everyday"],
    ["fiesta", "party", "everyday"],
    ["celebración", "celebration", "everyday"],
    // Travel (more)
    ["aduanero", "customs officer", "travel"],
    ["vuelo", "flight", "travel"],
    ["retraso", "delay (late)", "travel"],
    ["embarque", "boarding", "travel"],
    ["asiento", "seat", "travel"],
    ["ventanilla", "ticket window / small window", "travel"],
    ["peaje", "toll", "travel"],
    // Tech (more)
    ["cargador", "charger", "tech"],
    ["batería", "battery", "tech"],
    ["pantalla", "screen", "tech"],
    ["aplicación", "app", "tech"],
    ["archivo", "file", "tech"],
    ["carpeta", "folder (paper)", "tech"],
    ["enlace", "link", "tech"],
    ["error", "error", "tech"],
    // School / study
    ["libro", "book", "school"],
    ["cuaderno", "notebook", "school"],
    ["bolígrafo", "pen", "school"],
    ["lápiz", "pencil", "school"],
    ["profesor", "teacher (male)", "school"],
    ["profesora", "teacher (female)", "school"],
    ["universidad", "university", "school"],
    ["explicación", "explanation", "school"],
    // Body / health (more)
    ["espalda", "back", "body"],
    ["cuello", "neck", "body"],
    ["hombro", "shoulder", "body"],
    ["rodilla", "knee", "body"],
    ["sangre", "blood", "body"],
    ["hueso", "bone", "body"],
    ["consulta médica", "medical appointment", "health"],
    ["receta médica", "prescription", "health"],
    // Law / civic
    ["ley", "law", "civic"],
    ["policía", "police / police officer", "civic"],
    ["bombero", "firefighter", "civic"],
    ["violencia", "violence", "civic"],
    ["libertad", "freedom", "civic"],
    ["iguales", "equal", "civic"],
    // Abstract / connectors
    ["razón", "reason / to be right", "basics"],
    ["verdad", "truth / really", "basics"],
    ["mentira", "lie", "basics"],
    ["posible", "possible", "adjectives"],
    ["imposible", "impossible", "adjectives"],
    ["rápidamente", "quickly", "basics"],
    ["lentamente", "slowly", "basics"],
    ["casi", "almost", "basics"],
    ["demasiado", "too much / too many", "basics"],
    ["quizás", "perhaps", "basics"],
    ["además", "besides / also", "basics"],
    ["sin embargo", "however", "basics"],
    ["aunque", "although", "basics"],
    ["mientras", "while", "basics"],
    ["quizá", "maybe", "basics"],
  ];

  for (const [es, en, tag] of moreBulk) window.WORD_BANK.push({ es, en, tag });

  const evenMore = [
    // Numbers 11–100 (selected)
    ["once", "eleven", "numbers"],
    ["doce", "twelve", "numbers"],
    ["trece", "thirteen", "numbers"],
    ["catorce", "fourteen", "numbers"],
    ["quince", "fifteen", "numbers"],
    ["dieciséis", "sixteen", "numbers"],
    ["diecisiete", "seventeen", "numbers"],
    ["dieciocho", "eighteen", "numbers"],
    ["diecinueve", "nineteen", "numbers"],
    ["veinte", "twenty", "numbers"],
    ["treinta", "thirty", "numbers"],
    ["cuarenta", "forty", "numbers"],
    ["cincuenta", "fifty", "numbers"],
    ["cien", "one hundred", "numbers"],
    ["primero", "first", "numbers"],
    ["segundo", "second", "numbers"],
    ["tercero", "third", "numbers"],
    ["mitad", "half", "numbers"],
    ["doble", "double", "numbers"],
    ["par", "even number", "numbers"],
    ["impar", "odd number", "numbers"],
    // Time / calendar
    ["segundo (tiempo)", "second (time)", "time"],
    ["siglo", "century", "time"],
    ["época", "era / epoch", "time"],
    ["momento", "moment", "time"],
    ["pronto", "soon", "time"],
    ["tarjeta de embarque", "boarding pass", "travel"],
    ["pasillo", "aisle / hallway", "travel"],
    ["conexión", "flight connection", "travel"],
    ["demora", "delay (wait)", "travel"],
    ["itinerario", "itinerary", "travel"],
    ["guía turístico", "tour guide", "travel"],
    ["aerolínea", "airline", "travel"],
    // Food & drink (more)
    ["filete", "steak / fillet", "food"],
    ["chuleta", "chop / cutlet", "food"],
    ["jamón", "ham", "food"],
    ["tocino", "bacon", "food"],
    ["salchicha", "sausage", "food"],
    ["atún", "tuna", "food"],
    ["camarón", "shrimp", "food"],
    ["langosta", "lobster", "food"],
    ["mejillón", "mussel", "food"],
    ["ostra", "oyster", "food"],
    ["calamar", "squid", "food"],
    ["pulpo", "octopus", "food"],
    ["cordero", "lamb", "food"],
    ["ternera", "veal / beef", "food"],
    ["chocolate", "chocolate", "food"],
    ["galleta", "cookie / biscuit", "food"],
    ["pastel", "cake / pie", "food"],
    ["dulce", "sweet / candy", "food"],
    ["salado", "salty", "food"],
    ["picante", "spicy", "food"],
    ["amargo", "bitter", "food"],
    ["ácido", "sour / acidic", "food"],
    ["cocido", "boiled meal", "food"],
    ["guiso", "stew", "food"],
    ["sándwich", "sandwich", "food"],
    ["hamburguesa", "hamburger", "food"],
    ["tortilla española", "Spanish omelette", "food"],
    ["paella", "paella", "food"],
    ["gazpacho", "gazpacho", "food"],
    ["tapas", "tapas", "food"],
    ["brindis", "toast (cheers)", "food"],
    // Home & chores
    ["secadora", "clothes dryer", "home"],
    ["lavavajillas", "dishwasher", "home"],
    ["fregadero", "kitchen sink", "home"],
    ["grifo", "faucet / tap", "home"],
    ["tubo", "pipe", "home"],
    ["interruptor", "light switch", "home"],
    ["bombilla", "light bulb", "home"],
    ["vela", "candle", "home"],
    ["cojín", "cushion", "home"],
    ["manta", "blanket", "home"],
    ["almohada", "pillow", "home"],
    ["sábana", "bed sheet", "home"],
    ["colcha", "bedspread", "home"],
    ["percha", "hanger", "home"],
    ["tendedero", "clothesline", "home"],
    ["planchar", "to iron", "verbs"],
    ["lavar", "to wash", "verbs"],
    ["secar", "to dry", "verbs"],
    ["barrer", "to sweep", "verbs"],
    ["fregar", "to scrub / mop", "verbs"],
    // Body & health
    ["estómago", "stomach", "body"],
    ["hígado", "liver", "body"],
    ["riñón", "kidney", "body"],
    ["pulmón", "lung", "body"],
    ["cerebro", "brain", "body"],
    ["piel", "skin", "body"],
    ["uña", "fingernail", "body"],
    ["barba", "beard", "body"],
    ["bigote", "mustache", "body"],
    ["ceja", "eyebrow", "body"],
    ["pestaña", "eyelash", "body"],
    ["diente", "tooth", "body"],
    ["lengua", "tongue", "body"],
    ["garganta", "throat", "body"],
    ["muñeca", "wrist", "body"],
    ["tobillo", "ankle", "body"],
    ["cadera", "hip", "body"],
    ["codo", "elbow", "body"],
    ["dedo", "finger / toe", "body"],
    ["herida", "wound / injury", "health"],
    ["gripe", "flu", "health"],
    ["resfriado", "cold (illness)", "health"],
    ["pastilla", "pill / tablet", "health"],
    ["inyección", "injection", "health"],
    ["cita", "appointment / date", "health"],
    // Emotions & personality
    ["alegre", "cheerful", "feelings"],
    ["serio", "serious", "feelings"],
    ["simpático", "nice / friendly", "feelings"],
    ["antipático", "unpleasant", "feelings"],
    ["educado", "polite", "feelings"],
    ["grosero", "rude", "feelings"],
    ["tímido", "shy", "feelings"],
    ["extrovertido", "outgoing", "feelings"],
    ["introvertido", "introverted", "feelings"],
    ["paciente", "patient", "feelings"],
    ["impaciente", "impatient", "feelings"],
    ["egoísta", "selfish", "feelings"],
    ["generoso", "generous", "feelings"],
    ["celoso", "jealous", "feelings"],
    ["culpable", "guilty", "feelings"],
    ["inocente", "innocent", "feelings"],
    // Work & office
    ["ordenador", "computer (Spain)", "tech"],
    ["portátil", "laptop", "tech"],
    ["teclado", "keyboard", "tech"],
    ["ratón", "computer mouse", "tech"],
    ["impresora", "printer", "tech"],
    ["escáner", "scanner", "tech"],
    ["router", "router", "tech"],
    ["usuario", "user / username", "tech"],
    ["correo electrónico", "email", "tech"],
    ["mensaje", "message", "tech"],
    ["videollamada", "video call", "tech"],
    ["reunión virtual", "virtual meeting", "work"],
    ["currículum", "résumé / CV", "work"],
    ["entrevista", "interview", "work"],
    ["contrato", "contract", "work"],
    ["empresa", "company", "work"],
    ["cliente", "client", "work"],
    ["proveedor", "supplier", "work"],
    ["factura", "invoice / bill", "work"],
    ["plazo", "deadline / term", "work"],
    ["informe", "report", "work"],
    ["gráfico", "chart / graph", "work"],
    ["hoja de cálculo", "spreadsheet", "work"],
    ["presentación", "presentation", "work"],
    ["compañero de trabajo", "coworker", "work"],
    ["ascenso", "job promotion", "work"],
    ["despido", "layoff / firing", "work"],
    ["jubilación", "retirement", "work"],
    // School
    ["mochila", "backpack", "school"],
    ["estuche", "pencil case", "school"],
    ["pizarra", "blackboard / whiteboard", "school"],
    ["tiza", "chalk", "school"],
    ["rotulador", "marker", "school"],
    ["goma de borrar", "eraser", "school"],
    ["regla", "ruler", "school"],
    ["calculadora", "calculator", "school"],
    ["diccionario", "dictionary", "school"],
    ["biblioteca", "library", "school"],
    ["nota", "grade / note", "school"],
    ["beca", "scholarship", "school"],
    ["matrícula", "tuition / enrollment", "school"],
    // Nature & outdoors
    ["prado", "meadow", "nature"],
    ["colina", "hill", "nature"],
    ["valle", "valley", "nature"],
    ["cueva", "cave", "nature"],
    ["cascada", "waterfall", "nature"],
    ["isla", "island", "nature"],
    ["costa", "coast", "nature"],
    ["arena", "sand", "nature"],
    ["roca", "rock", "nature"],
    ["volcán", "volcano", "nature"],
    ["desierto", "desert", "nature"],
    ["pradera", "prairie", "nature"],
    ["campo", "field / countryside", "nature"],
    ["césped", "lawn / grass", "nature"],
    ["hierba", "grass / herb", "nature"],
    ["semilla", "seed", "nature"],
    ["raíz", "root", "nature"],
    ["hoja (árbol)", "leaf", "nature"],
    ["rama", "branch", "nature"],
    ["tronco", "tree trunk", "nature"],
    ["corteza", "bark", "nature"],
    ["musgo", "moss", "nature"],
    ["helecho", "fern", "nature"],
    ["cactus", "cactus", "nature"],
    // Animals
    ["tigre", "tiger", "animals"],
    ["león", "lion", "animals"],
    ["oso", "bear", "animals"],
    ["lobo", "wolf", "animals"],
    ["zorro", "fox", "animals"],
    ["conejo", "rabbit", "animals"],
    ["ardilla", "squirrel", "animals"],
    ["murciélago", "bat", "animals"],
    ["delfín", "dolphin", "animals"],
    ["ballena", "whale", "animals"],
    ["tiburón", "shark", "animals"],
    ["tortuga", "turtle / tortoise", "animals"],
    ["rana", "frog", "animals"],
    ["abeja", "bee", "animals"],
    ["mosca", "fly", "animals"],
    ["hormiga", "ant", "animals"],
    ["araña", "spider", "animals"],
    ["caracol", "snail", "animals"],
    ["burro", "donkey", "animals"],
    ["pato", "duck", "animals"],
    ["ganso", "goose", "animals"],
    ["gallina", "hen", "animals"],
    ["gallo", "rooster", "animals"],
    // Verbs (common)
    ["añadir", "to add", "verbs"],
    ["quitar", "to remove", "verbs"],
    ["sacar", "to take out", "verbs"],
    ["meter", "to put in", "verbs"],
    ["juntar", "to join / gather", "verbs"],
    ["separar", "to separate", "verbs"],
    ["reparar", "to repair", "verbs"],
    ["funcionar", "to function", "verbs"],
    ["fallar", "to fail", "verbs"],
    ["apagar", "to turn off", "verbs"],
    ["encender", "to turn on / light", "verbs"],
    ["conectar", "to connect", "verbs"],
    ["desconectar", "to disconnect", "verbs"],
    ["descargar", "to download / unload", "verbs"],
    ["subir (archivo)", "to upload", "verbs"],
    ["imprimir", "to print", "verbs"],
    ["firmar", "to sign", "verbs"],
    ["enviar", "to send", "verbs"],
    ["recibir", "to receive", "verbs"],
    ["devolver", "to return something", "verbs"],
    ["prestar", "to lend", "verbs"],
    ["pedir prestado", "to borrow", "verbs"],
    ["compartir", "to share", "verbs"],
    ["invitar", "to invite", "verbs"],
    ["celebrar", "to celebrate", "verbs"],
    ["sugerir", "to suggest", "verbs"],
    ["recomendar", "to recommend", "verbs"],
    ["admitir", "to admit", "verbs"],
    ["negar", "to deny", "verbs"],
    ["prometer", "to promise", "verbs"],
    ["cumplir", "to keep a promise", "verbs"],
    ["romper una promesa", "to break a promise", "phrases"],
    // Shopping & city
    ["centro comercial", "shopping mall", "shopping"],
    ["supermercado", "supermarket", "shopping"],
    ["cajero automático", "ATM", "shopping"],
    ["cola", "line / queue", "everyday"],
    ["turno", "turn / shift", "everyday"],
    ["cita previa", "prior appointment", "everyday"],
    ["vecino", "neighbor", "people"],
    ["vecina", "female neighbor", "people"],
    ["barrio", "neighborhood", "everyday"],
    ["centro", "downtown / center", "everyday"],
    ["afueras", "outskirts", "everyday"],
    ["esquina", "street corner", "everyday"],
    ["semáforo", "traffic light", "travel"],
    ["cruce", "crossing / intersection", "travel"],
    ["acera", "sidewalk", "travel"],
    ["bache", "pothole", "travel"],
    ["multa", "fine (ticket)", "travel"],
    ["licencia de conducir", "driver’s license", "travel"],
    ["cinturón de seguridad", "seat belt", "travel"],
    ["volante", "steering wheel", "travel"],
    ["neumático", "tire", "travel"],
    ["gasolina", "gasoline", "travel"],
    ["gasolinera", "gas station", "travel"],
    // Hobbies & media
    ["película", "movie / film", "media"],
    ["serie", "TV series", "media"],
    ["capítulo", "episode / chapter", "media"],
    ["actor", "actor", "media"],
    ["actriz", "actress", "media"],
    ["director", "director", "media"],
    ["cámara", "camera", "media"],
    ["fotografía", "photography", "media"],
    ["videojuego", "video game", "media"],
    ["música", "music", "media"],
    ["canción", "song", "media"],
    ["baile", "dance / dancing", "media"],
    ["dibujo", "drawing", "media"],
    ["pintura", "painting / paint", "media"],
    ["novela", "novel", "media"],
    ["poesía", "poetry", "media"],
    ["teatro", "theater", "media"],
    ["museo", "museum", "media"],
    ["exposición", "exhibition", "media"],
    // Household & misc
    ["cinta", "tape / ribbon", "everyday"],
    ["pegamento", "glue", "everyday"],
    ["tijeras", "scissors", "everyday"],
    ["cuerda", "rope / string", "everyday"],
    ["martillo", "hammer", "everyday"],
    ["clavo", "nail", "everyday"],
    ["tornillo", "screw", "everyday"],
    ["taladro", "drill", "everyday"],
    ["pintura (pared)", "wall paint", "home"],
    ["pincel", "paintbrush", "home"],
    ["escalera", "ladder", "home"],
    ["caja", "box", "everyday"],
    ["bolsa", "bag", "everyday"],
    ["cartera", "wallet", "shopping"],
    ["moneda", "coin", "shopping"],
    ["billete de banco", "paper money", "shopping"],
    // Abstract
    ["objetivo", "objective", "basics"],
    ["meta", "goal (aim)", "basics"],
    ["éxito", "success", "basics"],
    ["fracaso", "failure", "basics"],
    ["esfuerzo", "effort", "basics"],
    ["suerte", "luck", "basics"],
    ["riesgo", "risk", "basics"],
    ["ventaja", "advantage", "basics"],
    ["desventaja", "disadvantage", "basics"],
    ["consejo", "advice", "basics"],
    ["opinión", "opinion", "basics"],
    ["acuerdo", "agreement", "basics"],
    ["desacuerdo", "disagreement", "basics"],
    ["discusión", "argument / discussion", "basics"],
    ["pelea", "fight", "basics"],
    ["paz", "peace", "basics"],
    ["guerra", "war", "basics"],
    ["frontera", "border / frontier", "civic"],
    ["gobierno", "government", "civic"],
    ["presidente", "president", "civic"],
    ["elección", "election", "civic"],
    ["voto", "a vote", "civic"],
    ["leyenda", "legend", "basics"],
    ["cuento", "tale / short story", "basics"],
    ["historia", "history / story", "basics"],
    ["cuento de hadas", "fairy tale", "basics"],
    // Phrases
    ["me alegro", "I'm glad", "phrases"],
    ["lo siento mucho", "I'm very sorry", "phrases"],
    ["en serio", "seriously / really?", "phrases"],
    ["por supuesto", "certainly", "phrases"],
    ["en realidad", "actually / in reality", "phrases"],
    ["al menos", "at least", "phrases"],
    ["de repente", "suddenly", "phrases"],
    ["de vez en cuando", "from time to time", "phrases"],
    ["a menudo", "often", "phrases"],
    ["casi nunca", "almost never", "phrases"],
    ["cuanto antes", "as soon as possible", "phrases"],
    ["hace falta", "it's necessary / one needs", "phrases"],
    ["me da igual", "it's all the same to me", "phrases"],
    ["¡ojo!", "watch out!", "phrases"],
    ["¡cuidado!", "careful!", "phrases"],
    ["feliz cumpleaños", "happy birthday", "phrases"],
    ["felices fiestas", "happy holidays", "phrases"],
    ["buena suerte", "good luck", "phrases"],
    ["mala suerte", "bad luck", "phrases"],
    ["enhorabuena", "congratulations", "phrases"],
    ["salud (brindis)", "cheers", "phrases"],
  ];

  for (const [es, en, tag] of evenMore) window.WORD_BANK.push({ es, en, tag });

  // Plain, simple words to round out thin topics (sports, civic, weather, etc.).
  const topicBoostV1 = [
    // Sports
    ["pelota", "ball", "sports"],
    ["balón", "soccer ball", "sports"],
    ["raqueta", "racket", "sports"],
    ["gol", "goal (sports)", "sports"],
    ["punto", "point", "sports"],
    ["empate", "tie (draw)", "sports"],
    ["derrota", "loss", "sports"],
    ["atleta", "athlete", "sports"],
    ["piscina", "pool", "sports"],
    ["béisbol", "baseball", "sports"],
    ["voleibol", "volleyball", "sports"],
    ["golf", "golf", "sports"],
    ["boxeo", "boxing", "sports"],
    ["medalla", "medal", "sports"],
    ["estadio", "stadium", "sports"],
    ["árbitro", "referee", "sports"],
    ["aficionado", "fan", "sports"],
    ["campeonato", "championship", "sports"],
    ["jugador", "player", "sports"],
    ["entrenador", "coach", "sports"],
    ["capitán", "captain", "sports"],
    ["portero", "goalkeeper", "sports"],
    ["cancha", "court", "sports"],
    ["red", "net", "sports"],
    ["carrera", "race", "sports"],
    ["maratón", "marathon", "sports"],
    ["yoga", "yoga", "sports"],
    ["patinaje", "skating", "sports"],
    ["esquí", "skiing", "sports"],
    ["surf", "surfing", "sports"],
    ["corredor", "runner", "sports"],
    ["nadador", "swimmer", "sports"],
    ["camiseta", "sports shirt", "sports"],
    ["zapatillas", "sneakers", "sports"],
    ["sudor", "sweat", "sports"],
    ["calentamiento", "warm-up", "sports"],
    ["hockey", "hockey", "sports"],
    ["rugby", "rugby", "sports"],
    // Civic
    ["bandera", "flag", "civic"],
    ["alcalde", "mayor", "civic"],
    ["ciudadano", "citizen", "civic"],
    ["juez", "judge", "civic"],
    ["crimen", "crime", "civic"],
    ["comunidad", "community", "civic"],
    ["justicia", "justice", "civic"],
    ["democracia", "democracy", "civic"],
    ["república", "republic", "civic"],
    ["ministerio", "ministry", "civic"],
    ["seguridad", "security", "civic"],
    ["prisión", "prison", "civic"],
    ["robo", "theft", "civic"],
    ["ladrón", "thief", "civic"],
    ["derecho", "right (legal)", "civic"],
    ["deber", "duty", "civic"],
    ["norma", "rule", "civic"],
    ["ayuntamiento", "city hall", "civic"],
    ["embajada", "embassy", "civic"],
    ["impuesto", "tax", "civic"],
    ["ayuda", "help", "civic"],
    ["voluntario", "volunteer", "civic"],
    ["ciudadano activo", "active citizen", "civic"],
    // Weather
    ["tormenta", "storm", "weather"],
    ["niebla", "fog", "weather"],
    ["arcoíris", "rainbow", "weather"],
    ["nublado", "cloudy", "weather"],
    ["soleado", "sunny", "weather"],
    ["lluvioso", "rainy", "weather"],
    ["ventoso", "windy", "weather"],
    ["húmedo", "humid", "weather"],
    ["seco", "dry", "weather"],
    ["temperatura", "temperature", "weather"],
    ["primavera", "spring", "weather"],
    ["verano", "summer", "weather"],
    ["otoño", "autumn", "weather"],
    ["invierno", "winter", "weather"],
    ["clima", "climate", "weather"],
    ["granizo", "hail", "weather"],
    ["helada", "icy / frost", "weather"],
    // Colors
    ["dorado", "gold", "colors"],
    ["plateado", "silver", "colors"],
    ["beige", "beige", "colors"],
    ["turquesa", "turquoise", "colors"],
    ["luz", "light", "colors"],
    ["oscuro", "dark", "colors"],
    ["color", "color", "colors"],
    ["tez", "skin tone", "colors"],
    // Adjectives
    ["alto", "tall", "adjectives"],
    ["bajo", "short", "adjectives"],
    ["largo", "long", "adjectives"],
    ["corto", "brief", "adjectives"],
    ["gordo", "fat", "adjectives"],
    ["delgado", "thin", "adjectives"],
    ["joven", "young", "adjectives"],
    ["mayor", "older", "adjectives"],
    ["hambriento", "hungry", "adjectives"],
    ["sediento", "thirsty", "adjectives"],
    ["amable", "kind", "adjectives"],
    ["inteligente", "smart", "adjectives"],
    ["tonto", "silly", "adjectives"],
    ["cruel", "cruel", "adjectives"],
    ["salado", "salty", "adjectives"],
    ["suave", "soft", "adjectives"],
    ["duro", "hard", "adjectives"],
    ["rico", "rich", "adjectives"],
    ["pobre", "poor", "adjectives"],
    ["cómodo", "comfortable", "adjectives"],
    ["incómodo", "uncomfortable", "adjectives"],
    ["ruidoso", "loud", "adjectives"],
    ["silencioso", "quiet", "adjectives"],
    ["antiguo", "ancient", "adjectives"],
    ["moderno", "modern", "adjectives"],
    ["caliente", "hot", "adjectives"],
    // Health
    ["ambulancia", "ambulance", "health"],
    ["enfermedad", "illness", "health"],
    ["saludable", "healthy", "health"],
    ["dentista", "dentist", "health"],
    ["termómetro", "thermometer", "health"],
    ["mascarilla", "face mask", "health"],
    ["emergencia", "emergency", "health"],
    ["curita", "bandage", "health"],
    ["mareo", "dizziness", "health"],
    ["vitamina", "vitamin", "health"],
    ["descanso", "rest", "health"],
    ["sanar", "to heal", "health"],
    ["recuperarse", "to get better", "health"],
    ["malestar", "discomfort", "health"],
    // Shopping
    ["rebaja", "sale", "shopping"],
    ["carrito", "shopping cart", "shopping"],
    ["caja registradora", "checkout", "shopping"],
    ["etiqueta", "price tag", "shopping"],
    ["cambio", "change", "shopping"],
    ["baratillo", "bargain", "shopping"],
    ["probador", "fitting room", "shopping"],
    ["devolución", "return", "shopping"],
    ["lista de compras", "shopping list", "shopping"],
    ["vitrina", "shop window", "shopping"],
    // Clothes
    ["pantalón", "pants (one pair)", "clothes"],
    ["corbata", "tie (necktie)", "clothes"],
    ["cinturón", "belt", "clothes"],
    ["pijama", "pajamas", "clothes"],
    ["bañador", "swimsuit", "clothes"],
    ["collar", "necklace", "clothes"],
    ["botas", "boots", "clothes"],
    ["sandalias", "sandals", "clothes"],
    ["pantalones cortos", "shorts", "clothes"],
    ["talla", "size", "clothes"],
    ["moda", "fashion", "clothes"],
    // Tech
    ["wifi", "wifi", "tech"],
    ["enlace", "link", "tech"],
    ["archivo", "file", "tech"],
    ["carpeta digital", "folder (digital)", "tech"],
    ["correo electrónico", "email", "tech"],
    ["tableta", "tablet", "tech"],
    ["auriculares", "headphones", "tech"],
    ["altavoz", "speaker", "tech"],
    ["impresora", "printer", "tech"],
    ["ratón inalámbrico", "wireless mouse", "tech"],
    // Media
    ["radio", "radio", "media"],
    ["noticias", "news", "media"],
    ["canal", "channel", "media"],
    ["concierto", "concert", "media"],
    ["guitarra", "guitar", "media"],
    ["piano", "piano", "media"],
    ["tambor", "drum", "media"],
    ["violín", "violin", "media"],
    ["programa", "TV show", "media"],
    ["revista", "magazine", "media"],
    ["periódico", "newspaper", "media"],
    ["historieta", "comic", "media"],
    // School
    ["alumno", "student", "school"],
    ["estudiante", "pupil", "school"],
    ["lección", "lesson", "school"],
    ["curso", "course", "school"],
    ["aula", "classroom", "school"],
    ["asignatura", "subject", "school"],
    ["deberes", "homework (deberes)", "school"],
    ["recreo", "recess", "school"],
    ["graduación", "graduation", "school"],
    ["pupitre", "desk", "school"],
    ["examen oral", "oral exam", "school"],
    // Work
    ["trabajador", "worker", "work"],
    ["ocupación", "job", "work"],
    ["pausa", "break", "work"],
    ["uniforme", "uniform", "work"],
    ["herramienta", "tool", "work"],
    // Animals
    ["mono", "monkey", "animals"],
    ["jirafa", "giraffe", "animals"],
    ["cebra", "zebra", "animals"],
    ["pingüino", "penguin", "animals"],
    ["águila", "eagle", "animals"],
    ["hormiga", "ant", "animals"],
    ["cangrejo", "crab", "animals"],
    ["tortuga", "turtle", "animals"],
    ["loro", "parrot", "animals"],
    ["canguro", "kangaroo", "animals"],
    // Nature
    ["colina", "hill", "nature"],
    ["valle", "valley", "nature"],
    ["desierto", "desert", "nature"],
    ["cascada", "waterfall", "nature"],
    ["roca", "rock", "nature"],
    ["arena", "sand", "nature"],
    ["hierba", "grass", "nature"],
    ["planta", "plant", "nature"],
    // Feelings
    ["orgulloso", "proud", "feelings"],
    ["avergonzado", "embarrassed", "feelings"],
    ["emocionado", "excited", "feelings"],
    ["aburrimiento", "boredom", "feelings"],
    ["sorprendido", "surprised", "feelings"],
    ["preocupado", "worried", "feelings"],
    ["tranquilo", "calm", "feelings"],
    ["estresado", "stressed", "feelings"],
    // Phrases
    ["¿cómo estás?", "how are you?", "phrases"],
    ["mucho gusto", "nice to meet you", "phrases"],
    ["nos vemos", "see you", "phrases"],
    ["me llamo", "my name is", "phrases"],
    ["con permiso", "excuse me", "phrases"],
    ["¡ánimo!", "cheer up!", "phrases"],
    ["¡felicidades!", "congratulations!", "phrases"],
    ["buen trabajo", "good job", "phrases"],
    ["estoy cansado", "I am tired", "phrases"],
  ];

  for (const [es, en, tag] of topicBoostV1) window.WORD_BANK.push({ es, en, tag });

  // Keep the deck approachable: drop specialist tags and obscure English.
  const EXCLUDE_TAGS = new Set(["neuro", "muscles", "office"]);
  const MAX_SINGLE_EN = 16;
  const MAX_DISPLAY_EN = 45;

  function displayEnForFilter(en) {
    if (typeof window.primaryEnglish === "function") return window.primaryEnglish(en);
    return String(en ?? "").trim();
  }

  function isTooAdvanced(w) {
    const tag = String(w.tag || "").toLowerCase();
    if (EXCLUDE_TAGS.has(tag)) return true;

    const en = displayEnForFilter(w.en);
    if (!en) return false;

    const words = en.split(/\s+/);
    if (words.length === 1 && words[0].length > MAX_SINGLE_EN) return true;
    if (en.length > MAX_DISPLAY_EN) return true;
    if (words.length > 5) return true;

    return false;
  }

  window.WORD_BANK = window.WORD_BANK.filter((w) => !isTooAdvanced(w));

  // De-duplicate (same Spanish) while keeping the first occurrence.
  const seen = new Set();
  window.WORD_BANK = window.WORD_BANK.filter((w) => {
    const key = String(w.es).trim().toLowerCase();
    if (!key) return false;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  try {
    if (typeof window.dispatchEvent === "function") {
      window.dispatchEvent(new Event("wordbankready"));
    }
  } catch (e) {
    /* ignore */
  }
})();

