/* global window */
(() => {
  "use strict";

  /**
   * Word object shape:
   * { es: string, en: string, tag?: string }
   *
   * Keep this list large and practical. You can add more inside the app too.
   */
  window.WORD_BANK = [
    // Core / greetings
    { es: "hola", en: "hello", tag: "basics" },
    { es: "adiós", en: "goodbye", tag: "basics" },
    { es: "por favor", en: "please", tag: "basics" },
    { es: "gracias", en: "thank you", tag: "basics" },
    { es: "de nada", en: "you're welcome", tag: "basics" },
    { es: "perdón", en: "sorry / excuse me", tag: "basics" },
    { es: "lo siento", en: "I'm sorry", tag: "basics" },
    { es: "buenos días", en: "good morning", tag: "basics" },
    { es: "buenas tardes", en: "good afternoon", tag: "basics" },
    { es: "buenas noches", en: "good night", tag: "basics" },
    { es: "¿qué tal?", en: "how's it going?", tag: "basics" },
    { es: "¿cómo estás?", en: "how are you?", tag: "basics" },
    { es: "bien", en: "well / fine", tag: "basics" },
    { es: "mal", en: "badly", tag: "basics" },
    { es: "más o menos", en: "so-so", tag: "basics" },
    { es: "¿cómo te llamas?", en: "what's your name?", tag: "basics" },
    { es: "me llamo…", en: "my name is…", tag: "basics" },
    { es: "mucho gusto", en: "nice to meet you", tag: "basics" },
    { es: "encantado/a", en: "pleased to meet you", tag: "basics" },
    { es: "¿de dónde eres?", en: "where are you from?", tag: "basics" },
    { es: "soy de…", en: "I'm from…", tag: "basics" },
    { es: "sí", en: "yes", tag: "basics" },
    { es: "no", en: "no", tag: "basics" },
    { es: "tal vez", en: "maybe", tag: "basics" },
    { es: "claro", en: "of course", tag: "basics" },
    { es: "vale", en: "okay / alright", tag: "basics" },
    { es: "bienvenido/a", en: "welcome", tag: "basics" },
    { es: "salud", en: "cheers / bless you", tag: "basics" },

    // Numbers / time
    { es: "uno", en: "one", tag: "numbers" },
    { es: "dos", en: "two", tag: "numbers" },
    { es: "tres", en: "three", tag: "numbers" },
    { es: "cuatro", en: "four", tag: "numbers" },
    { es: "cinco", en: "five", tag: "numbers" },
    { es: "seis", en: "six", tag: "numbers" },
    { es: "siete", en: "seven", tag: "numbers" },
    { es: "ocho", en: "eight", tag: "numbers" },
    { es: "nueve", en: "nine", tag: "numbers" },
    { es: "diez", en: "ten", tag: "numbers" },
    { es: "hoy", en: "today", tag: "time" },
    { es: "mañana", en: "tomorrow", tag: "time" },
    { es: "ayer", en: "yesterday", tag: "time" },
    { es: "ahora", en: "now", tag: "time" },
    { es: "luego", en: "later", tag: "time" },
    { es: "antes", en: "before", tag: "time" },
    { es: "después", en: "after", tag: "time" },
    { es: "siempre", en: "always", tag: "time" },
    { es: "nunca", en: "never", tag: "time" },
    { es: "a veces", en: "sometimes", tag: "time" },
    { es: "temprano", en: "early", tag: "time" },
    { es: "tarde", en: "late", tag: "time" },

    // People / pronouns
    { es: "yo", en: "I", tag: "people" },
    { es: "tú", en: "you (informal)", tag: "people" },
    { es: "usted", en: "you (formal)", tag: "people" },
    { es: "él", en: "he", tag: "people" },
    { es: "ella", en: "she", tag: "people" },
    { es: "nosotros", en: "we", tag: "people" },
    { es: "nosotras", en: "we (fem.)", tag: "people" },
    { es: "ellos", en: "they (masc.)", tag: "people" },
    { es: "ellas", en: "they (fem.)", tag: "people" },
    { es: "mi", en: "my", tag: "people" },
    { es: "tu", en: "your (informal)", tag: "people" },
    { es: "su", en: "his/her/your/their", tag: "people" },

    // Common verbs (infinitives)
    { es: "ser", en: "to be (essential)", tag: "verbs" },
    { es: "estar", en: "to be (state/location)", tag: "verbs" },
    { es: "tener", en: "to have", tag: "verbs" },
    { es: "hacer", en: "to do / to make", tag: "verbs" },
    { es: "ir", en: "to go", tag: "verbs" },
    { es: "venir", en: "to come", tag: "verbs" },
    { es: "ver", en: "to see", tag: "verbs" },
    { es: "mirar", en: "to look at / watch", tag: "verbs" },
    { es: "oír", en: "to hear", tag: "verbs" },
    { es: "escuchar", en: "to listen", tag: "verbs" },
    { es: "hablar", en: "to speak", tag: "verbs" },
    { es: "decir", en: "to say / to tell", tag: "verbs" },
    { es: "preguntar", en: "to ask", tag: "verbs" },
    { es: "responder", en: "to answer", tag: "verbs" },
    { es: "poder", en: "to be able to / can", tag: "verbs" },
    { es: "querer", en: "to want / to love", tag: "verbs" },
    { es: "necesitar", en: "to need", tag: "verbs" },
    { es: "gustar", en: "to like (pleases)", tag: "verbs" },
    { es: "amar", en: "to love", tag: "verbs" },
    { es: "comer", en: "to eat", tag: "verbs" },
    { es: "beber", en: "to drink", tag: "verbs" },
    { es: "vivir", en: "to live", tag: "verbs" },
    { es: "trabajar", en: "to work", tag: "verbs" },
    { es: "estudiar", en: "to study", tag: "verbs" },
    { es: "leer", en: "to read", tag: "verbs" },
    { es: "escribir", en: "to write", tag: "verbs" },
    { es: "aprender", en: "to learn", tag: "verbs" },
    { es: "enseñar", en: "to teach", tag: "verbs" },
    { es: "comprar", en: "to buy", tag: "verbs" },
    { es: "vender", en: "to sell", tag: "verbs" },
    { es: "pagar", en: "to pay", tag: "verbs" },
    { es: "abrir", en: "to open", tag: "verbs" },
    { es: "cerrar", en: "to close", tag: "verbs" },
    { es: "empezar", en: "to start", tag: "verbs" },
    { es: "terminar", en: "to finish", tag: "verbs" },
    { es: "llevar", en: "to carry / to wear", tag: "verbs" },
    { es: "poner", en: "to put / to place", tag: "verbs" },
    { es: "dar", en: "to give", tag: "verbs" },
    { es: "tomar", en: "to take / to drink", tag: "verbs" },
    { es: "usar", en: "to use", tag: "verbs" },
    { es: "ayudar", en: "to help", tag: "verbs" },
    { es: "buscar", en: "to look for", tag: "verbs" },
    { es: "encontrar", en: "to find", tag: "verbs" },
    { es: "esperar", en: "to wait / to hope", tag: "verbs" },
    { es: "llamar", en: "to call", tag: "verbs" },
    { es: "llegar", en: "to arrive", tag: "verbs" },
    { es: "salir", en: "to leave / go out", tag: "verbs" },
    { es: "entrar", en: "to enter", tag: "verbs" },
    { es: "volver", en: "to return", tag: "verbs" },
    { es: "viajar", en: "to travel", tag: "verbs" },
    { es: "conocer", en: "to know (a person/place)", tag: "verbs" },
    { es: "saber", en: "to know (a fact)", tag: "verbs" },
    { es: "pensar", en: "to think", tag: "verbs" },
    { es: "creer", en: "to believe", tag: "verbs" },
    { es: "sentir", en: "to feel", tag: "verbs" },
    { es: "dormir", en: "to sleep", tag: "verbs" },

    // Travel / directions
    { es: "aquí", en: "here", tag: "travel" },
    { es: "allí", en: "there", tag: "travel" },
    { es: "izquierda", en: "left", tag: "travel" },
    { es: "derecha", en: "right", tag: "travel" },
    { es: "recto", en: "straight", tag: "travel" },
    { es: "cerca", en: "near", tag: "travel" },
    { es: "lejos", en: "far", tag: "travel" },
    { es: "mapa", en: "map", tag: "travel" },
    { es: "calle", en: "street", tag: "travel" },
    { es: "ciudad", en: "city", tag: "travel" },
    { es: "país", en: "country", tag: "travel" },
    { es: "aeropuerto", en: "airport", tag: "travel" },
    { es: "boleto", en: "ticket", tag: "travel" },
    { es: "pasaporte", en: "passport", tag: "travel" },
    { es: "hotel", en: "hotel", tag: "travel" },
    { es: "habitación", en: "room", tag: "travel" },
    { es: "reserva", en: "reservation", tag: "travel" },

    // Food
    { es: "agua", en: "water", tag: "food" },
    { es: "café", en: "coffee", tag: "food" },
    { es: "té", en: "tea", tag: "food" },
    { es: "leche", en: "milk", tag: "food" },
    { es: "pan", en: "bread", tag: "food" },
    { es: "arroz", en: "rice", tag: "food" },
    { es: "pollo", en: "chicken", tag: "food" },
    { es: "carne", en: "meat", tag: "food" },
    { es: "pescado", en: "fish", tag: "food" },
    { es: "verduras", en: "vegetables", tag: "food" },
    { es: "fruta", en: "fruit", tag: "food" },
    { es: "manzana", en: "apple", tag: "food" },
    { es: "plátano", en: "banana", tag: "food" },
    { es: "naranja", en: "orange", tag: "food" },
    { es: "queso", en: "cheese", tag: "food" },
    { es: "huevo", en: "egg", tag: "food" },
    { es: "azúcar", en: "sugar", tag: "food" },
    { es: "sal", en: "salt", tag: "food" },
    { es: "pimienta", en: "pepper", tag: "food" },
    { es: "aceite", en: "oil", tag: "food" },
    { es: "vinagre", en: "vinegar", tag: "food" },

    // Home
    { es: "casa", en: "house", tag: "home" },
    { es: "apartamento", en: "apartment", tag: "home" },
    { es: "puerta", en: "door", tag: "home" },
    { es: "ventana", en: "window", tag: "home" },
    { es: "cocina", en: "kitchen", tag: "home" },
    { es: "baño", en: "bathroom", tag: "home" },
    { es: "dormitorio", en: "bedroom", tag: "home" },
    { es: "sala", en: "living room", tag: "home" },
    { es: "mesa", en: "table", tag: "home" },
    { es: "silla", en: "chair", tag: "home" },
    { es: "cama", en: "bed", tag: "home" },
    { es: "llave", en: "key", tag: "home" },

    // Adjectives
    { es: "bueno", en: "good", tag: "adjectives" },
    { es: "malo", en: "bad", tag: "adjectives" },
    { es: "grande", en: "big", tag: "adjectives" },
    { es: "pequeño", en: "small", tag: "adjectives" },
    { es: "nuevo", en: "new", tag: "adjectives" },
    { es: "viejo", en: "old", tag: "adjectives" },
    { es: "bonito", en: "pretty", tag: "adjectives" },
    { es: "feo", en: "ugly", tag: "adjectives" },
    { es: "fácil", en: "easy", tag: "adjectives" },
    { es: "difícil", en: "difficult", tag: "adjectives" },
    { es: "rápido", en: "fast", tag: "adjectives" },
    { es: "lento", en: "slow", tag: "adjectives" },
    { es: "caro", en: "expensive", tag: "adjectives" },
    { es: "barato", en: "cheap", tag: "adjectives" },

    // Connectors / useful words
    { es: "y", en: "and", tag: "basics" },
    { es: "o", en: "or", tag: "basics" },
    { es: "pero", en: "but", tag: "basics" },
    { es: "porque", en: "because", tag: "basics" },
    { es: "para", en: "for / in order to", tag: "basics" },
    { es: "con", en: "with", tag: "basics" },
    { es: "sin", en: "without", tag: "basics" },
    { es: "muy", en: "very", tag: "basics" },
    { es: "también", en: "also", tag: "basics" },
    { es: "solo", en: "only / alone", tag: "basics" },
    { es: "todavía", en: "still", tag: "basics" },
    { es: "ya", en: "already / now", tag: "basics" },

    // Expand quickly with a practical starter bank (~250+ items)
    // Body
    { es: "cabeza", en: "head", tag: "body" },
    { es: "cara", en: "face", tag: "body" },
    { es: "ojo", en: "eye", tag: "body" },
    { es: "nariz", en: "nose", tag: "body" },
    { es: "boca", en: "mouth", tag: "body" },
    { es: "mano", en: "hand", tag: "body" },
    { es: "brazo", en: "arm", tag: "body" },
    { es: "pierna", en: "leg", tag: "body" },
    { es: "pie", en: "foot", tag: "body" },
    { es: "corazón", en: "heart", tag: "body" },

    // Weather
    { es: "tiempo", en: "weather / time", tag: "weather" },
    { es: "sol", en: "sun", tag: "weather" },
    { es: "lluvia", en: "rain", tag: "weather" },
    { es: "viento", en: "wind", tag: "weather" },
    { es: "nieve", en: "snow", tag: "weather" },
    { es: "calor", en: "heat", tag: "weather" },
    { es: "frío", en: "cold", tag: "weather" },

    // Work / school
    { es: "trabajo", en: "job / work", tag: "work" },
    { es: "oficina", en: "office", tag: "work" },
    { es: "reunión", en: "meeting", tag: "work" },
    { es: "correo", en: "mail / email", tag: "work" },
    { es: "escuela", en: "school", tag: "school" },
    { es: "clase", en: "class", tag: "school" },
    { es: "tarea", en: "homework", tag: "school" },
    { es: "examen", en: "exam", tag: "school" },

    // More everyday nouns
    { es: "amigo", en: "friend", tag: "people" },
    { es: "familia", en: "family", tag: "people" },
    { es: "niño", en: "boy / child", tag: "people" },
    { es: "niña", en: "girl / child", tag: "people" },
    { es: "hombre", en: "man", tag: "people" },
    { es: "mujer", en: "woman", tag: "people" },
    { es: "persona", en: "person", tag: "people" },
    { es: "nombre", en: "name", tag: "basics" },
    { es: "palabra", en: "word", tag: "basics" },
    { es: "pregunta", en: "question", tag: "basics" },
    { es: "respuesta", en: "answer", tag: "basics" },
    { es: "problema", en: "problem", tag: "basics" },
    { es: "idea", en: "idea", tag: "basics" },

    // Transport
    { es: "coche", en: "car", tag: "travel" },
    { es: "autobús", en: "bus", tag: "travel" },
    { es: "tren", en: "train", tag: "travel" },
    { es: "metro", en: "subway", tag: "travel" },
    { es: "bicicleta", en: "bicycle", tag: "travel" },

    // Clothes
    { es: "ropa", en: "clothes", tag: "clothes" },
    { es: "camisa", en: "shirt", tag: "clothes" },
    { es: "pantalones", en: "pants", tag: "clothes" },
    { es: "zapatos", en: "shoes", tag: "clothes" },
    { es: "chaqueta", en: "jacket", tag: "clothes" },

    // Tech
    { es: "teléfono", en: "phone", tag: "tech" },
    { es: "computadora", en: "computer", tag: "tech" },
    { es: "internet", en: "internet", tag: "tech" },
    { es: "contraseña", en: "password", tag: "tech" },

    // A big chunk of high-frequency words (curated, compact)
    { es: "hoy", en: "today", tag: "time" },
    { es: "mañana (la mañana)", en: "morning", tag: "time" },
    { es: "noche", en: "night", tag: "time" },
    { es: "semana", en: "week", tag: "time" },
    { es: "mes", en: "month", tag: "time" },
    { es: "año", en: "year", tag: "time" },
    { es: "hora", en: "hour", tag: "time" },
    { es: "minuto", en: "minute", tag: "time" },

    { es: "uno (una)", en: "one / a", tag: "basics" },
    { es: "este", en: "this", tag: "basics" },
    { es: "ese", en: "that", tag: "basics" },
    { es: "aquel", en: "that (over there)", tag: "basics" },
    { es: "aquí", en: "here", tag: "basics" },
    { es: "ahí", en: "there", tag: "basics" },

    // (More will be appended programmatically below)
  ];

  // Add lots of additional everyday vocabulary without bloating manual edits.
  // This keeps the file readable while still giving you a big bank.
  const extra = [
    // Home + objects
    ["cuchara", "spoon", "home"],
    ["tenedor", "fork", "home"],
    ["cuchillo", "knife", "home"],
    ["plato", "plate", "home"],
    ["vaso", "glass", "home"],
    ["taza", "cup", "home"],
    ["botella", "bottle", "home"],
    ["toalla", "towel", "home"],
    ["jabón", "soap", "home"],
    ["ducha", "shower", "home"],
    ["espejo", "mirror", "home"],
    ["refrigerador", "fridge", "home"],
    ["horno", "oven", "home"],
    ["estufa", "stove", "home"],
    ["cortina", "curtain", "home"],
    ["pared", "wall", "home"],
    ["suelo", "floor", "home"],
    ["techo", "ceiling", "home"],

    // Food / restaurant
    ["desayuno", "breakfast", "food"],
    ["almuerzo", "lunch", "food"],
    ["cena", "dinner", "food"],
    ["restaurante", "restaurant", "food"],
    ["menú", "menu", "food"],
    ["cuenta", "bill / check", "food"],
    ["propina", "tip", "food"],
    ["hambre", "hunger", "food"],
    ["sed", "thirst", "food"],

    // Travel
    ["estación", "station", "travel"],
    ["parada", "stop", "travel"],
    ["taxi", "taxi", "travel"],
    ["billete", "ticket / banknote", "travel"],
    ["maleta", "suitcase", "travel"],
    ["equipaje", "luggage", "travel"],
    ["aduana", "customs", "travel"],

    // Feelings
    ["feliz", "happy", "feelings"],
    ["triste", "sad", "feelings"],
    ["cansado", "tired", "feelings"],
    ["enfermo", "sick", "feelings"],
    ["ocupado", "busy", "feelings"],
    ["nervioso", "nervous", "feelings"],
    ["emocionado", "excited", "feelings"],

    // Common phrases
    ["no entiendo", "I don't understand", "phrases"],
    ["no sé", "I don't know", "phrases"],
    ["¿puedes repetir?", "can you repeat?", "phrases"],
    ["más despacio", "more slowly", "phrases"],
    ["¿qué significa…?", "what does … mean?", "phrases"],
    ["¿dónde está…?", "where is …?", "phrases"],
    ["¿cuánto cuesta?", "how much does it cost?", "phrases"],
    ["¿qué hora es?", "what time is it?", "phrases"],
    ["tengo hambre", "I'm hungry", "phrases"],
    ["tengo sed", "I'm thirsty", "phrases"],

    // More high-frequency nouns (everyday)
    ["tienda", "store", "everyday"],
    ["mercado", "market", "everyday"],
    ["banco", "bank", "everyday"],
    ["hospital", "hospital", "everyday"],
    ["farmacia", "pharmacy", "everyday"],
    ["iglesia", "church", "everyday"],
    ["parque", "park", "everyday"],
    ["playa", "beach", "everyday"],
    ["montaña", "mountain", "everyday"],
    ["río", "river", "everyday"],
    ["mar", "sea", "everyday"],
    ["lago", "lake", "everyday"],
    ["bosque", "forest", "everyday"],
    ["árbol", "tree", "everyday"],
    ["flor", "flower", "everyday"],
    ["perro", "dog", "everyday"],
    ["gato", "cat", "everyday"],
    ["pájaro", "bird", "everyday"],
    ["caballo", "horse", "everyday"],
    ["pez", "fish", "everyday"],
    ["calle", "street", "everyday"],
    ["carretera", "road", "everyday"],
    ["puente", "bridge", "everyday"],
    ["plaza", "square", "everyday"],

    // Shopping / money
    ["dinero", "money", "shopping"],
    ["precio", "price", "shopping"],
    ["oferta", "sale / offer", "shopping"],
    ["descuento", "discount", "shopping"],
    ["tarjeta", "card", "shopping"],
    ["efectivo", "cash", "shopping"],
    ["cambio", "change", "shopping"],
    ["recibo", "receipt", "shopping"],

    // Health
    ["médico", "doctor", "health"],
    ["enfermera", "nurse", "health"],
    ["medicina", "medicine", "health"],
    ["dolor", "pain", "health"],
    ["fiebre", "fever", "health"],
    ["tos", "cough", "health"],
    ["alergia", "allergy", "health"],

    // Common adjectives (more)
    ["importante", "important", "adjectives"],
    ["interesante", "interesting", "adjectives"],
    ["aburrido", "boring", "adjectives"],
    ["fuerte", "strong", "adjectives"],
    ["débil", "weak", "adjectives"],
    ["limpio", "clean", "adjectives"],
    ["sucio", "dirty", "adjectives"],
    ["lleno", "full", "adjectives"],
    ["vacío", "empty", "adjectives"],
    ["correcto", "correct", "adjectives"],
    ["equivocado", "wrong", "adjectives"],
    ["abierto", "open", "adjectives"],
    ["cerrado", "closed", "adjectives"],
    ["seguro", "safe / sure", "adjectives"],
    ["peligroso", "dangerous", "adjectives"],

    // Common verbs (more)
    ["caminar", "to walk", "verbs"],
    ["correr", "to run", "verbs"],
    ["conducir", "to drive", "verbs"],
    ["cocinar", "to cook", "verbs"],
    ["llover", "to rain", "verbs"],
    ["llorar", "to cry", "verbs"],
    ["reír", "to laugh", "verbs"],
    ["pagar", "to pay", "verbs"],
    ["ganar", "to win / earn", "verbs"],
    ["perder", "to lose", "verbs"],
    ["dejar", "to leave / let", "verbs"],
    ["intentar", "to try", "verbs"],
    ["explicar", "to explain", "verbs"],
    ["recordar", "to remember", "verbs"],
    ["olvidar", "to forget", "verbs"],
    ["cambiar", "to change", "verbs"],
    ["mejorar", "to improve", "verbs"],
    ["decidir", "to decide", "verbs"],
    ["elegir", "to choose", "verbs"],

    // More useful phrases
    ["¿puedes ayudarme?", "can you help me?", "phrases"],
    ["¿hablas inglés?", "do you speak English?", "phrases"],
    ["hablo un poco de español", "I speak a little Spanish", "phrases"],
    ["no hay problema", "no problem", "phrases"],
    ["¡qué suerte!", "how lucky!", "phrases"],
    ["¡qué pena!", "what a shame!", "phrases"],
    ["hasta luego", "see you later", "phrases"],
    ["hasta mañana", "see you tomorrow", "phrases"],
    ["buen viaje", "have a good trip", "phrases"],
  ];

  for (const [es, en, tag] of extra) window.WORD_BANK.push({ es, en, tag });

  const moreBulk = [
    // Clothing & colors
    ["abrigo", "coat", "clothes"],
    ["sombrero", "hat", "clothes"],
    ["gorra", "cap", "clothes"],
    ["calcetines", "socks", "clothes"],
    ["falda", "skirt", "clothes"],
    ["vestido", "dress", "clothes"],
    ["traje", "suit", "clothes"],
    ["jersey", "sweater / jersey", "clothes"],
    ["bufanda", "scarf", "clothes"],
    ["guantes", "gloves", "clothes"],
    ["blanco", "white", "colors"],
    ["negro", "black", "colors"],
    ["rojo", "red", "colors"],
    ["azul", "blue", "colors"],
    ["verde", "green", "colors"],
    ["amarillo", "yellow", "colors"],
    ["naranja", "orange", "colors"],
    ["morado", "purple", "colors"],
    ["rosa", "pink", "colors"],
    ["marrón", "brown", "colors"],
    ["gris", "gray", "colors"],
    // Food (more)
    ["sopa", "soup", "food"],
    ["ensalada", "salad", "food"],
    ["pasta", "pasta", "food"],
    ["pizza", "pizza", "food"],
    ["helado", "ice cream", "food"],
    ["mantequilla", "butter", "food"],
    ["miel", "honey", "food"],
    ["mermelada", "jam", "food"],
    ["salsa", "sauce", "food"],
    ["pimientos", "bell peppers", "food"],
    ["patata", "potato", "food"],
    ["tomate", "tomato", "food"],
    ["cebolla", "onion", "food"],
    ["ajo", "garlic", "food"],
    ["limón", "lemon", "food"],
    ["limonada", "lemonade", "food"],
    ["vino", "wine", "food"],
    ["cerveza", "beer", "food"],
    ["jugo", "juice", "food"],
    // Home (more)
    ["sofa", "sofa / couch", "home"],
    ["alfombra", "rug / carpet", "home"],
    ["lámpara", "lamp", "home"],
    ["enchufe", "outlet / plug", "home"],
    ["basura", "garbage / trash", "home"],
    ["escoba", "broom", "home"],
    ["detergente", "detergent", "home"],
    ["edificio", "building", "everyday"],
    ["ascensor", "elevator", "everyday"],
    ["escaleras", "stairs", "everyday"],
    // Sports & leisure
    ["fútbol", "soccer / football", "sports"],
    ["baloncesto", "basketball", "sports"],
    ["tenis", "tennis", "sports"],
    ["natación", "swimming", "sports"],
    ["bicicleta", "bicycle", "sports"],
    ["gimnasio", "gym", "sports"],
    ["partido", "match / game", "sports"],
    ["equipo", "team", "sports"],
    ["victoria", "victory", "sports"],
    ["ejercicio", "exercise", "sports"],
    // Nature / animals
    ["vaca", "cow", "animals"],
    ["cerdo", "pig", "animals"],
    ["oveja", "sheep", "animals"],
    ["rata", "rat", "animals"],
    ["serpiente", "snake", "animals"],
    ["insecto", "insect", "animals"],
    ["mariposa", "butterfly", "animals"],
    ["luna", "moon", "nature"],
    ["estrella", "star", "nature"],
    ["cielo", "sky", "nature"],
    ["nube", "cloud", "nature"],
    ["trueno", "thunder", "nature"],
    ["relámpago", "lightning", "nature"],
    ["terremoto", "earthquake", "nature"],
    // Professions
    ["ingeniero", "engineer", "work"],
    ["abogado", "lawyer", "work"],
    ["cocinero", "cook / chef", "work"],
    ["conductor", "driver", "work"],
    ["vendedor", "salesperson", "work"],
    ["cajero", "cashier", "work"],
    ["jefe", "boss", "work"],
    ["empleado", "employee", "work"],
    ["sueldo", "salary / wage", "work"],
    ["horario", "schedule", "work"],
    // Verbs / daily
    ["despertarse", "to wake up", "verbs"],
    ["vestirse", "to get dressed", "verbs"],
    ["ducharse", "to shower", "verbs"],
    ["desayunar", "to have breakfast", "verbs"],
    ["almorzar", "to have lunch", "verbs"],
    ["cenar", "to have dinner", "verbs"],
    ["subir", "to go up / to upload", "verbs"],
    ["bajar", "to go down / to lower", "verbs"],
    ["cruzar", "to cross", "verbs"],
    ["fumar", "to smoke", "verbs"],
    ["sufrir", "to suffer", "verbs"],
    ["soñar", "to dream", "verbs"],
    ["acostarse", "to go to bed / to lie down", "verbs"],
    ["llenar", "to fill", "verbs"],
    ["vaciar", "to empty", "verbs"],
    ["romper", "to break", "verbs"],
    ["arreglar", "to fix / to arrange", "verbs"],
    ["construir", "to build", "verbs"],
    ["votar", "to vote", "verbs"],
    ["proteger", "to protect", "verbs"],
    // Emotions / social
    ["enojado", "angry", "feelings"],
    ["asustado", "scared", "feelings"],
    ["avergonzado", "embarrassed", "feelings"],
    ["orgulloso", "proud", "feelings"],
    ["preocupado", "worried", "feelings"],
    ["tranquilo", "calm / relaxed", "feelings"],
    ["sorpresa", "surprise", "feelings"],
    ["abrazo", "hug", "people"],
    ["beso", "kiss", "people"],
    ["regalo", "gift", "everyday"],
    ["fiesta", "party", "everyday"],
    ["celebración", "celebration", "everyday"],
    // Travel (more)
    ["aduanero", "customs officer", "travel"],
    ["vuelo", "flight", "travel"],
    ["retraso", "delay", "travel"],
    ["embarque", "boarding", "travel"],
    ["asiento", "seat", "travel"],
    ["ventanilla", "ticket window / small window", "travel"],
    ["peaje", "toll", "travel"],
    // Tech (more)
    ["cargador", "charger", "tech"],
    ["batería", "battery", "tech"],
    ["pantalla", "screen", "tech"],
    ["aplicación", "app", "tech"],
    ["archivo", "file", "tech"],
    ["carpeta", "folder", "tech"],
    ["enlace", "link", "tech"],
    ["error", "error", "tech"],
    // School / study
    ["libro", "book", "school"],
    ["cuaderno", "notebook", "school"],
    ["bolígrafo", "pen", "school"],
    ["lápiz", "pencil", "school"],
    ["profesor", "teacher (male)", "school"],
    ["profesora", "teacher (female)", "school"],
    ["universidad", "university", "school"],
    ["explicación", "explanation", "school"],
    // Body / health (more)
    ["espalda", "back (body)", "body"],
    ["cuello", "neck", "body"],
    ["hombro", "shoulder", "body"],
    ["rodilla", "knee", "body"],
    ["sangre", "blood", "body"],
    ["hueso", "bone", "body"],
    ["consulta médica", "medical appointment", "health"],
    ["receta médica", "prescription", "health"],
    // Law / civic
    ["ley", "law", "civic"],
    ["policía", "police / police officer", "civic"],
    ["bombero", "firefighter", "civic"],
    ["violencia", "violence", "civic"],
    ["libertad", "freedom", "civic"],
    ["iguales", "equal (people)", "civic"],
    // Abstract / connectors
    ["razón", "reason / to be right", "basics"],
    ["verdad", "truth / really", "basics"],
    ["mentira", "lie", "basics"],
    ["posible", "possible", "adjectives"],
    ["imposible", "impossible", "adjectives"],
    ["rápidamente", "quickly", "basics"],
    ["lentamente", "slowly", "basics"],
    ["casi", "almost", "basics"],
    ["demasiado", "too much / too many", "basics"],
    ["quizás", "maybe", "basics"],
    ["además", "besides / also", "basics"],
    ["sin embargo", "however", "basics"],
    ["aunque", "although", "basics"],
    ["mientras", "while", "basics"],
    ["quizá", "perhaps", "basics"],
  ];

  for (const [es, en, tag] of moreBulk) window.WORD_BANK.push({ es, en, tag });

  const evenMore = [
    // Numbers 11–100 (selected)
    ["once", "eleven", "numbers"],
    ["doce", "twelve", "numbers"],
    ["trece", "thirteen", "numbers"],
    ["catorce", "fourteen", "numbers"],
    ["quince", "fifteen", "numbers"],
    ["dieciséis", "sixteen", "numbers"],
    ["diecisiete", "seventeen", "numbers"],
    ["dieciocho", "eighteen", "numbers"],
    ["diecinueve", "nineteen", "numbers"],
    ["veinte", "twenty", "numbers"],
    ["treinta", "thirty", "numbers"],
    ["cuarenta", "forty", "numbers"],
    ["cincuenta", "fifty", "numbers"],
    ["cien", "one hundred", "numbers"],
    ["primero", "first", "numbers"],
    ["segundo", "second", "numbers"],
    ["tercero", "third", "numbers"],
    ["mitad", "half", "numbers"],
    ["doble", "double", "numbers"],
    ["par", "even (number)", "numbers"],
    ["impar", "odd (number)", "numbers"],
    // Time / calendar
    ["segundo (tiempo)", "second (time unit)", "time"],
    ["siglo", "century", "time"],
    ["época", "era / epoch", "time"],
    ["momento", "moment", "time"],
    ["pronto", "soon", "time"],
    ["tarjeta de embarque", "boarding pass", "travel"],
    ["pasillo", "aisle / hallway", "travel"],
    ["conexión", "connection (flight)", "travel"],
    ["demora", "delay", "travel"],
    ["itinerario", "itinerary", "travel"],
    ["guía turístico", "tour guide", "travel"],
    ["aerolínea", "airline", "travel"],
    // Food & drink (more)
    ["filete", "steak / fillet", "food"],
    ["chuleta", "chop / cutlet", "food"],
    ["jamón", "ham", "food"],
    ["tocino", "bacon", "food"],
    ["salchicha", "sausage", "food"],
    ["atún", "tuna", "food"],
    ["camarón", "shrimp", "food"],
    ["langosta", "lobster", "food"],
    ["mejillón", "mussel", "food"],
    ["ostra", "oyster", "food"],
    ["calamar", "squid", "food"],
    ["pulpo", "octopus", "food"],
    ["cordero", "lamb", "food"],
    ["ternera", "veal / beef", "food"],
    ["chocolate", "chocolate", "food"],
    ["galleta", "cookie / biscuit", "food"],
    ["pastel", "cake / pie", "food"],
    ["dulce", "sweet / candy", "food"],
    ["salado", "salty", "food"],
    ["picante", "spicy", "food"],
    ["amargo", "bitter", "food"],
    ["ácido", "sour / acidic", "food"],
    ["cocido", "stew / boiled meal", "food"],
    ["guiso", "stew", "food"],
    ["sándwich", "sandwich", "food"],
    ["hamburguesa", "hamburger", "food"],
    ["tortilla española", "Spanish omelette", "food"],
    ["paella", "paella", "food"],
    ["gazpacho", "gazpacho", "food"],
    ["tapas", "tapas", "food"],
    ["brindis", "toast (cheers)", "food"],
    // Home & chores
    ["secadora", "dryer (machine)", "home"],
    ["lavavajillas", "dishwasher", "home"],
    ["fregadero", "kitchen sink", "home"],
    ["grifo", "faucet / tap", "home"],
    ["tubo", "pipe", "home"],
    ["interruptor", "light switch", "home"],
    ["bombilla", "light bulb", "home"],
    ["vela", "candle", "home"],
    ["cojín", "cushion", "home"],
    ["manta", "blanket", "home"],
    ["almohada", "pillow", "home"],
    ["sábana", "bed sheet", "home"],
    ["colcha", "bedspread", "home"],
    ["percha", "hanger", "home"],
    ["tendedero", "clothesline", "home"],
    ["planchar", "to iron", "verbs"],
    ["lavar", "to wash", "verbs"],
    ["secar", "to dry", "verbs"],
    ["barrer", "to sweep", "verbs"],
    ["fregar", "to scrub / mop", "verbs"],
    // Body & health
    ["estómago", "stomach", "body"],
    ["hígado", "liver", "body"],
    ["riñón", "kidney", "body"],
    ["pulmón", "lung", "body"],
    ["cerebro", "brain", "body"],
    ["piel", "skin", "body"],
    ["uña", "fingernail", "body"],
    ["barba", "beard", "body"],
    ["bigote", "mustache", "body"],
    ["ceja", "eyebrow", "body"],
    ["pestaña", "eyelash", "body"],
    ["diente", "tooth", "body"],
    ["lengua", "tongue", "body"],
    ["garganta", "throat", "body"],
    ["muñeca", "wrist", "body"],
    ["tobillo", "ankle", "body"],
    ["cadera", "hip", "body"],
    ["codo", "elbow", "body"],
    ["dedo", "finger / toe", "body"],
    ["herida", "wound / injury", "health"],
    ["gripe", "flu", "health"],
    ["resfriado", "cold (illness)", "health"],
    ["pastilla", "pill / tablet", "health"],
    ["inyección", "injection", "health"],
    ["cita", "appointment / date", "health"],
    // Emotions & personality
    ["alegre", "cheerful", "feelings"],
    ["serio", "serious", "feelings"],
    ["simpático", "nice / friendly", "feelings"],
    ["antipático", "unpleasant", "feelings"],
    ["educado", "polite", "feelings"],
    ["grosero", "rude", "feelings"],
    ["tímido", "shy", "feelings"],
    ["extrovertido", "outgoing", "feelings"],
    ["introvertido", "introverted", "feelings"],
    ["paciente", "patient", "feelings"],
    ["impaciente", "impatient", "feelings"],
    ["egoísta", "selfish", "feelings"],
    ["generoso", "generous", "feelings"],
    ["celoso", "jealous", "feelings"],
    ["culpable", "guilty", "feelings"],
    ["inocente", "innocent", "feelings"],
    // Work & office
    ["ordenador", "computer (Spain)", "tech"],
    ["portátil", "laptop", "tech"],
    ["teclado", "keyboard", "tech"],
    ["ratón", "mouse (computer)", "tech"],
    ["impresora", "printer", "tech"],
    ["escáner", "scanner", "tech"],
    ["router", "router", "tech"],
    ["usuario", "user / username", "tech"],
    ["correo electrónico", "email", "tech"],
    ["mensaje", "message", "tech"],
    ["videollamada", "video call", "tech"],
    ["reunión virtual", "virtual meeting", "work"],
    ["currículum", "résumé / CV", "work"],
    ["entrevista", "interview", "work"],
    ["contrato", "contract", "work"],
    ["empresa", "company", "work"],
    ["cliente", "client", "work"],
    ["proveedor", "supplier", "work"],
    ["factura", "invoice / bill", "work"],
    ["plazo", "deadline / term", "work"],
    ["informe", "report", "work"],
    ["gráfico", "chart / graph", "work"],
    ["hoja de cálculo", "spreadsheet", "work"],
    ["presentación", "presentation", "work"],
    ["compañero de trabajo", "coworker", "work"],
    ["ascenso", "promotion (job)", "work"],
    ["despido", "layoff / firing", "work"],
    ["jubilación", "retirement", "work"],
    // School
    ["mochila", "backpack", "school"],
    ["estuche", "pencil case", "school"],
    ["pizarra", "blackboard / whiteboard", "school"],
    ["tiza", "chalk", "school"],
    ["rotulador", "marker", "school"],
    ["goma de borrar", "eraser", "school"],
    ["regla", "ruler", "school"],
    ["calculadora", "calculator", "school"],
    ["diccionario", "dictionary", "school"],
    ["biblioteca", "library", "school"],
    ["nota", "grade / note", "school"],
    ["beca", "scholarship", "school"],
    ["matrícula", "tuition / enrollment", "school"],
    // Nature & outdoors
    ["prado", "meadow", "nature"],
    ["colina", "hill", "nature"],
    ["valle", "valley", "nature"],
    ["cueva", "cave", "nature"],
    ["cascada", "waterfall", "nature"],
    ["isla", "island", "nature"],
    ["costa", "coast", "nature"],
    ["arena", "sand", "nature"],
    ["roca", "rock", "nature"],
    ["volcán", "volcano", "nature"],
    ["desierto", "desert", "nature"],
    ["pradera", "prairie", "nature"],
    ["campo", "field / countryside", "nature"],
    ["césped", "lawn / grass", "nature"],
    ["hierba", "grass / herb", "nature"],
    ["semilla", "seed", "nature"],
    ["raíz", "root", "nature"],
    ["hoja (árbol)", "leaf", "nature"],
    ["rama", "branch", "nature"],
    ["tronco", "trunk (tree)", "nature"],
    ["corteza", "bark", "nature"],
    ["musgo", "moss", "nature"],
    ["helecho", "fern", "nature"],
    ["cactus", "cactus", "nature"],
    // Animals
    ["tigre", "tiger", "animals"],
    ["león", "lion", "animals"],
    ["oso", "bear", "animals"],
    ["lobo", "wolf", "animals"],
    ["zorro", "fox", "animals"],
    ["conejo", "rabbit", "animals"],
    ["ardilla", "squirrel", "animals"],
    ["murciélago", "bat", "animals"],
    ["delfín", "dolphin", "animals"],
    ["ballena", "whale", "animals"],
    ["tiburón", "shark", "animals"],
    ["tortuga", "turtle / tortoise", "animals"],
    ["rana", "frog", "animals"],
    ["abeja", "bee", "animals"],
    ["mosca", "fly", "animals"],
    ["hormiga", "ant", "animals"],
    ["araña", "spider", "animals"],
    ["caracol", "snail", "animals"],
    ["burro", "donkey", "animals"],
    ["pato", "duck", "animals"],
    ["ganso", "goose", "animals"],
    ["gallina", "hen", "animals"],
    ["gallo", "rooster", "animals"],
    // Verbs (common)
    ["añadir", "to add", "verbs"],
    ["quitar", "to remove", "verbs"],
    ["sacar", "to take out", "verbs"],
    ["meter", "to put in", "verbs"],
    ["juntar", "to join / gather", "verbs"],
    ["separar", "to separate", "verbs"],
    ["reparar", "to repair", "verbs"],
    ["funcionar", "to work / function", "verbs"],
    ["fallar", "to fail", "verbs"],
    ["apagar", "to turn off", "verbs"],
    ["encender", "to turn on / light", "verbs"],
    ["conectar", "to connect", "verbs"],
    ["desconectar", "to disconnect", "verbs"],
    ["descargar", "to download / unload", "verbs"],
    ["subir (archivo)", "to upload", "verbs"],
    ["imprimir", "to print", "verbs"],
    ["firmar", "to sign", "verbs"],
    ["enviar", "to send", "verbs"],
    ["recibir", "to receive", "verbs"],
    ["devolver", "to return (an item)", "verbs"],
    ["prestar", "to lend", "verbs"],
    ["pedir prestado", "to borrow", "verbs"],
    ["compartir", "to share", "verbs"],
    ["invitar", "to invite", "verbs"],
    ["celebrar", "to celebrate", "verbs"],
    ["sugerir", "to suggest", "verbs"],
    ["recomendar", "to recommend", "verbs"],
    ["admitir", "to admit", "verbs"],
    ["negar", "to deny", "verbs"],
    ["prometer", "to promise", "verbs"],
    ["cumplir", "to fulfill / keep (a promise)", "verbs"],
    ["romper una promesa", "to break a promise", "phrases"],
    // Shopping & city
    ["centro comercial", "shopping mall", "shopping"],
    ["supermercado", "supermarket", "shopping"],
    ["cajero automático", "ATM", "shopping"],
    ["cola", "line / queue", "everyday"],
    ["turno", "turn / shift", "everyday"],
    ["cita previa", "prior appointment", "everyday"],
    ["vecino", "neighbor", "people"],
    ["vecina", "neighbor (female)", "people"],
    ["barrio", "neighborhood", "everyday"],
    ["centro", "downtown / center", "everyday"],
    ["afueras", "outskirts", "everyday"],
    ["esquina", "corner (street)", "everyday"],
    ["semáforo", "traffic light", "travel"],
    ["cruce", "crossing / intersection", "travel"],
    ["acera", "sidewalk", "travel"],
    ["bache", "pothole", "travel"],
    ["multa", "fine (ticket)", "travel"],
    ["licencia de conducir", "driver’s license", "travel"],
    ["cinturón de seguridad", "seat belt", "travel"],
    ["volante", "steering wheel", "travel"],
    ["neumático", "tire", "travel"],
    ["gasolina", "gasoline", "travel"],
    ["gasolinera", "gas station", "travel"],
    // Hobbies & media
    ["película", "movie / film", "media"],
    ["serie", "TV series", "media"],
    ["capítulo", "episode / chapter", "media"],
    ["actor", "actor", "media"],
    ["actriz", "actress", "media"],
    ["director", "director", "media"],
    ["cámara", "camera", "media"],
    ["fotografía", "photography", "media"],
    ["videojuego", "video game", "media"],
    ["música", "music", "media"],
    ["canción", "song", "media"],
    ["baile", "dance / dancing", "media"],
    ["dibujo", "drawing", "media"],
    ["pintura", "painting / paint", "media"],
    ["novela", "novel", "media"],
    ["poesía", "poetry", "media"],
    ["teatro", "theater", "media"],
    ["museo", "museum", "media"],
    ["exposición", "exhibition", "media"],
    // Household & misc
    ["cinta", "tape / ribbon", "everyday"],
    ["pegamento", "glue", "everyday"],
    ["tijeras", "scissors", "everyday"],
    ["cuerda", "rope / string", "everyday"],
    ["martillo", "hammer", "everyday"],
    ["clavo", "nail", "everyday"],
    ["tornillo", "screw", "everyday"],
    ["taladro", "drill", "everyday"],
    ["pintura (pared)", "wall paint", "home"],
    ["pincel", "paintbrush", "home"],
    ["escalera", "ladder", "home"],
    ["caja", "box", "everyday"],
    ["bolsa", "bag", "everyday"],
    ["cartera", "wallet", "shopping"],
    ["moneda", "coin", "shopping"],
    ["billete de banco", "banknote", "shopping"],
    // Abstract
    ["objetivo", "goal / objective", "basics"],
    ["meta", "goal", "basics"],
    ["éxito", "success", "basics"],
    ["fracaso", "failure", "basics"],
    ["esfuerzo", "effort", "basics"],
    ["suerte", "luck", "basics"],
    ["riesgo", "risk", "basics"],
    ["ventaja", "advantage", "basics"],
    ["desventaja", "disadvantage", "basics"],
    ["consejo", "advice", "basics"],
    ["opinión", "opinion", "basics"],
    ["acuerdo", "agreement", "basics"],
    ["desacuerdo", "disagreement", "basics"],
    ["discusión", "argument / discussion", "basics"],
    ["pelea", "fight", "basics"],
    ["paz", "peace", "basics"],
    ["guerra", "war", "basics"],
    ["frontera", "border / frontier", "civic"],
    ["gobierno", "government", "civic"],
    ["presidente", "president", "civic"],
    ["elección", "election", "civic"],
    ["voto", "vote (noun)", "civic"],
    ["leyenda", "legend", "basics"],
    ["cuento", "tale / short story", "basics"],
    ["historia", "history / story", "basics"],
    ["cuento de hadas", "fairy tale", "basics"],
    // Phrases
    ["me alegro", "I'm glad", "phrases"],
    ["lo siento mucho", "I'm very sorry", "phrases"],
    ["en serio", "seriously / really?", "phrases"],
    ["por supuesto", "of course", "phrases"],
    ["en realidad", "actually / in reality", "phrases"],
    ["al menos", "at least", "phrases"],
    ["de repente", "suddenly", "phrases"],
    ["de vez en cuando", "from time to time", "phrases"],
    ["a menudo", "often", "phrases"],
    ["casi nunca", "almost never", "phrases"],
    ["cuanto antes", "as soon as possible", "phrases"],
    ["hace falta", "it's necessary / one needs", "phrases"],
    ["me da igual", "it's all the same to me", "phrases"],
    ["¡ojo!", "watch out!", "phrases"],
    ["¡cuidado!", "careful!", "phrases"],
    ["feliz cumpleaños", "happy birthday", "phrases"],
    ["felices fiestas", "happy holidays", "phrases"],
    ["buena suerte", "good luck", "phrases"],
    ["mala suerte", "bad luck", "phrases"],
    ["enhorabuena", "congratulations", "phrases"],
    ["salud (brindis)", "cheers", "phrases"],
  ];

  for (const [es, en, tag] of evenMore) window.WORD_BANK.push({ es, en, tag });

  const vocabExtraV2 = [
    ["archivador", "filing cabinet / ring binder", "office"],
    ["grapadora", "stapler", "office"],
    ["subrayador", "highlighter (pen)", "office"],
    ["carpeta", "folder", "office"],
    ["hoja suelta", "loose sheet", "office"],
    ["sobres", "envelopes", "office"],
    ["sello postal", "postage stamp", "office"],
    ["buzón", "mailbox", "everyday"],
    ["cartero", "mail carrier", "people"],
    ["paquete", "package / parcel", "shopping"],
    ["etiqueta", "label / tag", "everyday"],
    ["código de barras", "barcode", "tech"],
    ["código QR", "QR code", "tech"],
    ["contraseña", "password", "tech"],
    ["nombre de usuario", "username", "tech"],
    ["copia de seguridad", "backup (data)", "tech"],
    ["actualización", "update (software)", "tech"],
    ["desinstalar", "to uninstall", "verbs"],
    ["instalar", "to install", "verbs"],
    ["reiniciar", "to restart", "verbs"],
    ["apagar", "to turn off", "verbs"],
    ["encender", "to turn on / to light", "verbs"],
    ["enchufar", "to plug in", "verbs"],
    ["desenchufar", "to unplug", "verbs"],
    ["batería baja", "low battery", "tech"],
    ["cargador", "charger", "tech"],
    ["cable USB", "USB cable", "tech"],
    ["auriculares", "headphones", "tech"],
    ["micrófono", "microphone", "tech"],
    ["altavoz", "speaker (audio)", "tech"],
    ["pantalla táctil", "touchscreen", "tech"],
    ["deslizar", "to swipe", "verbs"],
    ["pulsar", "to tap (a button)", "verbs"],
    ["alfabeto", "alphabet", "school"],
    ["sílaba", "syllable", "school"],
    ["acento", "accent (stress mark)", "school"],
    ["sinónimo", "synonym", "school"],
    ["antónimo", "antonym", "school"],
    ["definición", "definition", "school"],
    ["oración", "sentence", "school"],
    ["párrafo", "paragraph", "school"],
    ["ensayo", "essay / trial", "school"],
    ["examen sorpresa", "pop quiz", "school"],
    ["materia", "school subject", "school"],
    ["asignatura", "course / subject", "school"],
    ["profesorado", "teaching staff", "school"],
    ["director de escuela", "principal (school)", "school"],
    ["mochila escolar", "school backpack", "school"],
    ["útiles escolares", "school supplies", "school"],
    ["pizarra digital", "digital whiteboard", "school"],
    ["tiza", "chalk", "school"],
    ["borrador de pizarra", "whiteboard eraser", "school"],
    ["regla", "ruler", "school"],
    ["compás", "compass (drawing)", "school"],
    ["transportador", "protractor", "school"],
    ["calculadora", "calculator", "school"],
    ["laboratorio", "laboratory", "school"],
    ["experimento", "experiment", "school"],
    ["hipótesis", "hypothesis", "school"],
    ["conclusión", "conclusion", "school"],
    ["bibliografía", "bibliography", "school"],
    ["mapa conceptual", "concept map", "school"],
    ["resumen", "summary", "school"],
    ["notas al pie", "footnotes", "school"],
    ["cita textual", "direct quote", "school"],
    ["parafrasear", "to paraphrase", "verbs"],
    ["redactar", "to draft / write up", "verbs"],
    ["corregir errores", "to correct mistakes", "verbs"],
    ["subir de nivel", "to level up / advance", "phrases"],
    ["bajar de nivel", "to drop a level", "phrases"],
    ["puesto de trabajo", "job position", "work"],
    ["contrato laboral", "employment contract", "work"],
    ["nómina", "payroll / payslip", "work"],
    ["vacaciones pagadas", "paid vacation", "work"],
    ["permiso parental", "parental leave", "work"],
    ["teletrabajo", "remote work", "work"],
    ["jornada laboral", "workday / shift hours", "work"],
    ["horas extras", "overtime hours", "work"],
    ["reunión virtual", "virtual meeting", "work"],
    ["minuta de reunión", "meeting minutes", "work"],
    ["orden del día", "agenda (of a meeting)", "work"],
    ["responsable del proyecto", "project lead", "work"],
    ["fecha límite", "deadline", "work"],
    ["entregable", "deliverable", "work"],
    ["retroalimentación", "feedback", "work"],
    ["evaluación de desempeño", "performance review", "work"],
    ["ascenso", "promotion (job)", "work"],
    ["despido", "layoff / firing", "work"],
    ["renuncia", "resignation", "work"],
    ["preaviso", "advance notice", "work"],
    ["indemnización", "severance pay / compensation", "work"],
    ["huelga", "strike (labor)", "work"],
    ["sindicato", "union (labor)", "work"],
    ["negociación", "negotiation", "work"],
    ["acuerdo verbal", "verbal agreement", "work"],
    ["firma electrónica", "electronic signature", "work"],
    ["cifrado", "encryption", "tech"],
    ["estafa en línea", "online scam", "tech"],
    ["phishing", "phishing", "tech"],
    ["cuenta hackeada", "hacked account", "tech"],
    ["verificación en dos pasos", "two-step verification", "tech"],
    ["caché del navegador", "browser cache", "tech"],
    ["historial de navegación", "browsing history", "tech"],
    ["modo incógnito", "private browsing mode", "tech"],
    ["marcador (web)", "bookmark (web)", "tech"],
    ["pestaña del navegador", "browser tab", "tech"],
    ["ventana emergente", "pop-up window", "tech"],
    ["cortafuegos", "firewall", "tech"],
    ["router", "router", "tech"],
    ["ancho de banda", "bandwidth", "tech"],
    ["latencia", "latency", "tech"],
    ["caída del servicio", "service outage", "tech"],
    ["mantenimiento programado", "scheduled maintenance", "tech"],
    ["copiar y pegar", "copy and paste", "tech"],
    ["cortar y pegar", "cut and paste", "tech"],
    ["deshacer", "to undo", "verbs"],
    ["rehacer", "to redo", "verbs"],
    ["autoguardado", "autosave", "tech"],
    ["plantilla", "template", "tech"],
    ["formato de archivo", "file format", "tech"],
    ["nube (informática)", "cloud (computing)", "tech"],
    ["sincronizar", "to sync", "verbs"],
    ["compartir enlace", "to share a link", "phrases"],
    ["descarga fallida", "failed download", "tech"],
    ["archivo adjunto", "email attachment", "tech"],
    ["bandeja de entrada", "inbox", "tech"],
    ["correo no deseado", "spam email", "tech"],
    ["marcar como leído", "to mark as read", "phrases"],
    ["silenciar notificaciones", "to mute notifications", "phrases"],
    ["modo avión", "airplane mode", "tech"],
    ["datos móviles", "mobile data", "tech"],
    ["zona sin cobertura", "dead zone (no signal)", "travel"],
    ["itinerario de vuelo", "flight itinerary", "travel"],
    ["maleta facturada", "checked bag", "travel"],
    ["equipaje de mano", "carry-on bag", "travel"],
    ["cinta transportadora", "baggage carousel / conveyor belt", "travel"],
    ["aduana", "customs", "travel"],
    ["declaración aduanera", "customs declaration", "travel"],
    ["visado", "visa (travel document)", "travel"],
    ["seguro de viaje", "travel insurance", "travel"],
    ["retraso prolongado", "lengthy delay", "travel"],
    ["vuelo cancelado", "cancelled flight", "travel"],
    ["sobreventa", "overbooking", "travel"],
    ["asiento de pasillo", "aisle seat", "travel"],
    ["asiento de ventanilla", "window seat", "travel"],
    ["cinturón abrochado", "seat belt fastened", "travel"],
    ["máscara de oxígeno", "oxygen mask", "travel"],
    ["chaleco salvavidas", "life jacket", "travel"],
    ["salida de emergencia", "emergency exit", "travel"],
    ["torre de control", "control tower", "travel"],
    ["pista de aterrizaje", "runway", "travel"],
    ["despegue", "takeoff (flight)", "travel"],
    ["aterrizaje", "landing (flight)", "travel"],
    ["turbulencia", "turbulence", "travel"],
    ["mareo", "motion sickness / dizziness", "body"],
    ["pastilla para el mareo", "motion sickness pill", "body"],
    ["botiquín", "first-aid kit", "body"],
    ["venda", "bandage", "body"],
    ["antiséptico", "antiseptic", "body"],
    ["termómetro", "thermometer", "body"],
    ["jarabe para la tos", "cough syrup", "body"],
    ["inhalador", "inhaler", "body"],
    ["alergia estacional", "seasonal allergy", "body"],
    ["picadura de insecto", "insect bite / sting", "body"],
    ["quemadura leve", "minor burn", "body"],
    ["esguince", "sprain", "body"],
    ["fractura", "fracture", "body"],
    ["fisioterapia", "physical therapy", "body"],
    ["reposo médico", "medical rest / sick leave note", "body"],
    ["cita médica", "doctor's appointment", "body"],
    ["ambulancia", "ambulance", "body"],
    ["urgencias", "emergency room", "body"],
    ["sala de espera", "waiting room", "everyday"],
    ["turno médico", "medical appointment slot", "body"],
    ["receta médica", "prescription", "body"],
    ["farmacia de guardia", "24-hour pharmacy", "body"],
    ["medicamento genérico", "generic medicine", "body"],
    ["efectos secundarios", "side effects", "body"],
    ["dosis", "dose", "body"],
    ["ayuno", "fasting", "food"],
    ["dieta equilibrada", "balanced diet", "food"],
    ["intolerancia a la lactosa", "lactose intolerance", "food"],
    ["sin gluten", "gluten-free", "food"],
    ["vegano", "vegan", "food"],
    ["vegetariano", "vegetarian", "food"],
    ["huerto urbano", "urban garden / allotment", "everyday"],
    ["compost", "compost", "everyday"],
    ["reciclaje", "recycling", "everyday"],
    ["contenedor amarillo", "recycling bin (yellow)", "everyday"],
    ["basura orgánica", "organic waste", "everyday"],
    ["punto limpio", "recycling drop-off center", "everyday"],
    ["huella de carbono", "carbon footprint", "nature"],
    ["energía renovable", "renewable energy", "nature"],
    ["panel solar", "solar panel", "nature"],
    ["contaminación lumínica", "light pollution", "nature"],
    ["especie en peligro", "endangered species", "nature"],
    ["deforestación", "deforestation", "nature"],
    ["sequía", "drought", "nature"],
    ["inundación", "flood", "nature"],
    ["evacuación", "evacuation", "civic"],
    ["refugio temporal", "temporary shelter", "civic"],
    ["voluntario", "volunteer", "civic"],
    ["donación de sangre", "blood donation", "civic"],
    ["campaña solidaria", "charity drive", "civic"],
    ["recaudación de fondos", "fundraising", "civic"],
    ["subasta benéfica", "charity auction", "civic"],
    ["testamento", "will (legal)", "civic"],
    ["herencia", "inheritance", "civic"],
    ["notario", "notary", "civic"],
    ["comparecencia", "court appearance", "civic"],
    ["multa de tráfico", "traffic fine", "civic"],
    ["defensa legal", "legal defense", "civic"],
    ["abogado de oficio", "public defender", "civic"],
    ["demanda judicial", "lawsuit", "civic"],
    ["acuerdo extrajudicial", "out-of-court settlement", "civic"],
    ["prueba documental", "documentary evidence", "civic"],
    ["cadena de custodia", "chain of custody", "civic"],
    ["testigo", "witness", "civic"],
    ["jurado", "jury", "civic"],
    ["veredicto", "verdict", "civic"],
    ["sentencia", "sentence (court ruling)", "civic"],
    ["apelación", "appeal (legal)", "civic"],
    ["libertad condicional", "parole", "civic"],
    ["pena de prisión", "prison sentence", "civic"],
    ["delito menor", "misdemeanor", "civic"],
    ["delito grave", "felony", "civic"],
    ["denuncia", "police report / complaint", "civic"],
    ["orden de alejamiento", "restraining order", "civic"],
    ["violencia doméstica", "domestic violence", "civic"],
    ["línea de ayuda", "helpline", "civic"],
    ["anonimato", "anonymity", "basics"],
    ["privacidad", "privacy", "basics"],
    ["consentimiento", "consent", "basics"],
    ["términos y condiciones", "terms and conditions", "basics"],
    ["política de privacidad", "privacy policy", "basics"],
    ["cookies (web)", "cookies (web)", "tech"],
    ["rastreador", "tracker (online)", "tech"],
    ["geolocalización", "geolocation", "tech"],
    ["permiso de ubicación", "location permission", "tech"],
    ["micrófono desactivado", "microphone muted", "tech"],
    ["cámara apagada", "camera off", "tech"],
    ["compartir pantalla", "screen sharing", "tech"],
    ["grabación de la reunión", "meeting recording", "work"],
    ["transcripción automática", "automatic transcription", "tech"],
    ["subtítulos en vivo", "live captions", "media"],
    ["doblaje", "dubbing", "media"],
    ["versión original", "original version (film)", "media"],
    ["crítica de cine", "film review", "media"],
    ["taquilla", "box office", "media"],
    ["estreno", "premiere / release", "media"],
    ["spoiler", "spoiler", "media"],
    ["temporada (serie)", "season (TV series)", "media"],
    ["binge-watching", "binge-watching", "media"],
    ["maratón de series", "TV marathon", "media"],
    ["lista de reproducción", "playlist", "media"],
    ["transmisión en vivo", "livestream", "media"],
    ["podcast", "podcast", "media"],
    ["audiolibro", "audiobook", "media"],
    ["e-reader", "e-reader", "media"],
    ["tableta gráfica", "graphics tablet", "media"],
    ["paleta de colores", "color palette", "media"],
    ["filtro (foto)", "filter (photo)", "media"],
    ["retoque digital", "digital retouching", "media"],
    ["meme", "meme", "media"],
    ["viral", "viral", "media"],
    ["influencer", "influencer", "media"],
    ["seguidores", "followers (social)", "media"],
    ["mención", "mention (social)", "media"],
    ["etiquetar", "to tag (someone)", "verbs"],
    ["bloquear usuario", "to block a user", "phrases"],
    ["denunciar contenido", "to report content", "phrases"],
    ["cuenta verificada", "verified account", "tech"],
    ["suplantación de identidad", "identity theft", "tech"],
    ["ingeniería social", "social engineering (fraud)", "tech"],
    ["contraseña segura", "strong password", "tech"],
    ["autenticación", "authentication", "tech"],
    ["token de acceso", "access token", "tech"],
    ["API", "API", "tech"],
    ["integración", "integration (software)", "tech"],
    ["registro de errores", "error log", "tech"],
    ["rastrear un fallo", "to trace a bug", "phrases"],
    ["parche de seguridad", "security patch", "tech"],
    ["vulnerabilidad", "vulnerability", "tech"],
    ["exploit", "exploit (security)", "tech"],
    ["ingeniero de software", "software engineer", "work"],
    ["desarrollador web", "web developer", "work"],
    ["diseñador UX", "UX designer", "work"],
    ["product manager", "product manager", "work"],
    ["analista de datos", "data analyst", "work"],
    ["científico de datos", "data scientist", "work"],
    ["inteligencia artificial", "artificial intelligence", "tech"],
    ["aprendizaje automático", "machine learning", "tech"],
    ["modelo predictivo", "predictive model", "tech"],
    ["sesgo algorítmico", "algorithmic bias", "tech"],
    ["ética de los datos", "data ethics", "tech"],
    ["anonimizar datos", "to anonymize data", "phrases"],
    ["cumplimiento normativo", "regulatory compliance", "work"],
    ["auditoría", "audit", "work"],
    ["fraude contable", "accounting fraud", "work"],
    ["balance contable", "balance sheet", "work"],
    ["flujo de caja", "cash flow", "work"],
    ["presupuesto anual", "annual budget", "work"],
    ["recorte presupuestario", "budget cut", "work"],
    ["inflación", "inflation", "basics"],
    ["deflación", "deflation", "basics"],
    ["tipos de interés", "interest rates", "basics"],
    ["hipoteca", "mortgage", "basics"],
    ["alquiler con opción a compra", "rent-to-own", "basics"],
    ["aval bancario", "bank guarantee", "basics"],
    ["transferencia bancaria", "bank transfer", "shopping"],
    ["divisa", "currency", "shopping"],
    ["tipo de cambio", "exchange rate", "shopping"],
    ["comisión", "fee / commission", "shopping"],
    ["reembolso", "refund", "shopping"],
    ["vale de descuento", "discount voucher", "shopping"],
    ["canjear", "to redeem (a coupon)", "verbs"],
    ["garantía del fabricante", "manufacturer warranty", "shopping"],
    ["arrepentimiento de compra", "buyer's remorse", "shopping"],
    ["devolución sin preguntas", "no-questions return policy", "shopping"],
    ["ticket de compra", "purchase receipt", "shopping"],
    ["factura simplificada", "simplified invoice", "shopping"],
    ["IVA incluido", "VAT included", "shopping"],
    ["propina obligatoria", "mandatory service charge", "food"],
    ["menú del día", "daily menu (restaurant)", "food"],
    ["carta de vinos", "wine list", "food"],
    ["maridaje", "food and wine pairing", "food"],
    ["intolerancia", "intolerance (food/medical)", "food"],
    ["alérgeno", "allergen", "food"],
    ["trazas de frutos secos", "may contain traces of nuts", "food"],
    ["cocina de autor", "fine dining / chef-driven cuisine", "food"],
    ["comida para llevar", "takeout food", "food"],
    ["pedido a domicilio", "home delivery order", "food"],
    ["repartidor", "delivery person", "people"],
    ["propina al repartidor", "tip for the delivery driver", "food"],
    ["valoración", "rating / review score", "everyday"],
    ["reseña", "review (written)", "everyday"],
    ["estrella (valoración)", "star (rating)", "everyday"],
    ["comentario tóxico", "toxic comment", "everyday"],
    ["moderador", "moderator (online)", "everyday"],
    ["normas de la comunidad", "community guidelines", "everyday"],
    ["acoso en línea", "online harassment", "everyday"],
    ["ciberacoso", "cyberbullying", "everyday"],
    ["denunciar", "to report (to authorities)", "verbs"],
    ["prueba fehaciente", "conclusive proof", "civic"],
    ["cadena de mensajes", "message thread", "tech"],
    ["hilo (foro)", "thread (forum)", "tech"],
    ["mensaje directo", "direct message", "tech"],
    ["grupo de chat", "chat group", "tech"],
    ["videollamada grupal", "group video call", "tech"],
    ["compartir ubicación en tiempo real", "live location sharing", "phrases"],
    ["modo oscuro", "dark mode", "tech"],
    ["modo claro", "light mode", "tech"],
    ["accesibilidad", "accessibility", "tech"],
    ["lector de pantalla", "screen reader", "tech"],
    ["contraste alto", "high contrast", "tech"],
    ["tamaño de fuente", "font size", "tech"],
    ["atajo de teclado", "keyboard shortcut", "tech"],
    ["barra de herramientas", "toolbar", "tech"],
    ["menú contextual", "context menu", "tech"],
    ["arrastrar y soltar", "drag and drop", "tech"],
    ["archivo corrupto", "corrupt file", "tech"],
    ["espacio en disco", "disk space", "tech"],
    ["memoria RAM", "RAM memory", "tech"],
    ["procesador", "processor (CPU)", "tech"],
    ["tarjeta gráfica", "graphics card", "tech"],
    ["refrigeración líquida", "liquid cooling", "tech"],
    ["sobrecalentamiento", "overheating", "tech"],
    ["ventilador", "fan (cooling)", "home"],
    ["ruido de fondo", "background noise", "everyday"],
    ["cancelación de ruido", "noise cancellation", "tech"],
    ["transcripción", "transcript", "work"],
    ["acta", "minutes / official record", "work"],
    ["rúbrica", "rubric (grading)", "school"],
    ["calificación final", "final grade", "school"],
    ["beca de estudios", "scholarship", "school"],
    ["matrícula universitaria", "university enrollment / tuition fee", "school"],
    ["campus", "campus", "school"],
    ["residencia estudiantil", "student dorm", "school"],
    ["compañero de piso", "roommate / flatmate", "people"],
    ["repartir gastos", "to split expenses", "phrases"],
    ["hoja de cálculo", "spreadsheet", "work"],
    ["fórmula", "formula", "school"],
    ["gráfico de barras", "bar chart", "work"],
    ["gráfico circular", "pie chart", "work"],
    ["tendencia", "trend", "basics"],
    ["valor atípico", "outlier (statistics)", "school"],
    ["muestra pequeña", "small sample", "school"],
    ["sesgo de selección", "selection bias", "school"],
    ["causalidad", "causality", "school"],
    ["correlación", "correlation", "school"],
    ["variable dependiente", "dependent variable", "school"],
    ["variable independiente", "independent variable", "school"],
    ["tabla de datos", "data table", "tech"],
    ["exportar a CSV", "to export to CSV", "phrases"],
    ["importar datos", "to import data", "phrases"],
    ["duplicados", "duplicates", "tech"],
    ["fusionar celdas", "to merge cells", "phrases"],
    ["congelar fila", "to freeze a row (spreadsheet)", "phrases"],
    ["pivote", "pivot (table)", "work"],
    ["cuadro de mando", "dashboard (metrics)", "work"],
    ["indicador clave", "key indicator / KPI", "work"],
    ["objetivo trimestral", "quarterly goal", "work"],
    ["hoja de ruta", "roadmap", "work"],
    ["alcance del proyecto", "project scope", "work"],
    ["fuera de alcance", "out of scope", "work"],
    ["dependencia (proyecto)", "dependency (project)", "work"],
    ["bloqueo", "blocker (project)", "work"],
    ["riesgo del proyecto", "project risk", "work"],
    ["plan de contingencia", "contingency plan", "work"],
    ["postmortem", "postmortem (review)", "work"],
    ["retrospectiva", "retrospective (team)", "work"],
    ["mejora continua", "continuous improvement", "work"],
    ["cultura de equipo", "team culture", "work"],
    ["sinergia", "synergy", "work"],
    ["alineación", "alignment (teams)", "work"],
    ["stakeholder", "stakeholder", "work"],
    ["partes interesadas", "stakeholders", "work"],
    ["comunicación asíncrona", "asynchronous communication", "work"],
    ["hilo de correo", "email thread", "work"],
    ["responder a todos", "reply all", "work"],
    ["correo en copia", "CC (email)", "work"],
    ["correo en copia oculta", "BCC (email)", "work"],
    ["asunto del correo", "email subject", "work"],
    ["firma de correo", "email signature", "work"],
    ["lista de distribución", "distribution list", "work"],
    ["calendario compartido", "shared calendar", "work"],
    ["franja horaria", "time slot", "work"],
    ["solapamiento", "overlap (scheduling)", "work"],
    ["confirmar asistencia", "to RSVP / confirm attendance", "phrases"],
    ["asistencia obligatoria", "mandatory attendance", "work"],
    ["justificante", "proof / certificate", "work"],
    ["ausencia justificada", "excused absence", "work"],
    ["baja laboral", "sick leave (from work)", "work"],
    ["incapacidad temporal", "temporary disability leave", "work"],
    ["mutua", "mutual insurance (Spain, health)", "body"],
    ["seguridad social", "social security", "civic"],
    ["número de afiliación", "membership number (social security)", "civic"],
    ["empadronamiento", "municipal registration (padrón)", "civic"],
    ["certificado de empadronamiento", "proof of address (padrón)", "civic"],
    ["DNI", "national ID card (Spain)", "civic"],
    ["NIE", "foreigner ID number (Spain)", "civic"],
    ["pasaporte caducado", "expired passport", "travel"],
    ["renovar el pasaporte", "to renew a passport", "phrases"],
    ["cita en consulado", "consulate appointment", "travel"],
    ["visado de estudiante", "student visa", "travel"],
    ["permiso de residencia", "residence permit", "civic"],
    ["tarjeta de residencia", "residence card", "civic"],
    ["extranjería", "immigration office", "civic"],
    ["nacionalidad", "nationality", "civic"],
    ["doble nacionalidad", "dual nationality", "civic"],
    ["ciudadanía", "citizenship", "civic"],
    ["voto por correo", "mail-in ballot", "civic"],
    ["urna", "ballot box", "civic"],
    ["recuento de votos", "vote count", "civic"],
    ["empate técnico", "dead heat / technical tie", "civic"],
    ["segunda vuelta", "runoff election", "civic"],
    ["coalición", "coalition (political)", "civic"],
    ["oposición", "opposition (political)", "civic"],
    ["mayoría absoluta", "absolute majority", "civic"],
    ["minoría", "minority (political)", "civic"],
    ["moción de censura", "vote of no confidence", "civic"],
    ["referéndum", "referendum", "civic"],
    ["plebiscito", "plebiscite", "civic"],
    ["encuesta electoral", "election poll", "civic"],
    ["margen de error", "margin of error", "civic"],
    ["muestra representativa", "representative sample", "civic"],
    ["sesgo político", "political bias", "civic"],
    ["desinformación", "disinformation", "civic"],
    ["verificación de hechos", "fact-checking", "civic"],
    ["fuente fiable", "reliable source", "civic"],
    ["rumor", "rumor", "basics"],
    ["confirmación oficial", "official confirmation", "civic"],
    ["comunicado de prensa", "press release", "civic"],
    ["rueda de prensa", "press conference", "civic"],
    ["portavoz", "spokesperson", "civic"],
    ["embargo informativo", "news embargo", "civic"],
    ["filtración", "leak (information)", "civic"],
    ["periodismo de investigación", "investigative journalism", "civic"],
    ["titular sensacionalista", "clickbait headline", "media"],
    ["paywall", "paywall", "media"],
    ["suscripción digital", "digital subscription", "media"],
    ["prueba gratuita", "free trial", "shopping"],
    ["renovación automática", "auto-renewal", "shopping"],
    ["darse de baja", "to unsubscribe / cancel membership", "phrases"],
    ["reembolso parcial", "partial refund", "shopping"],
    ["cargo inesperado", "unexpected charge", "shopping"],
    ["disputa con el banco", "dispute with the bank", "shopping"],
    ["extracto bancario", "bank statement", "shopping"],
    ["saldo negativo", "negative balance", "shopping"],
    ["descubierto", "overdraft", "shopping"],
    ["intereses moratorios", "late payment interest", "shopping"],
    ["plan de pagos", "payment plan", "shopping"],
    ["cuota mensual", "monthly installment", "shopping"],
    ["entrada (evento)", "ticket (event)", "shopping"],
    ["agotado", "sold out", "shopping"],
    ["lista de espera", "waiting list", "shopping"],
    ["devolver entradas", "to return tickets", "phrases"],
    ["cambio de fecha", "date change (event)", "phrases"],
    ["reprogramación", "rescheduling", "everyday"],
    ["imprevisto", "unforeseen event", "basics"],
    ["imprevistos", "unexpected expenses", "basics"],
    ["fondo de emergencia", "emergency fund", "basics"],
    ["colchón financiero", "financial cushion", "basics"],
    ["ahorro a largo plazo", "long-term savings", "basics"],
    ["jubilación anticipada", "early retirement", "work"],
    ["pensión pública", "public pension", "civic"],
    ["plan privado de pensiones", "private pension plan", "basics"],
    ["cotización", "contribution (social security) / quote", "work"],
    ["base cotización", "contribution base (payroll)", "work"],
    ["salario bruto", "gross salary", "work"],
    ["salario neto", "net salary", "work"],
    ["retención fiscal", "tax withholding", "work"],
    ["declaración de la renta", "income tax return", "civic"],
    ["deducción fiscal", "tax deduction", "civic"],
    ["devolución de impuestos", "tax refund", "civic"],
    ["inspección fiscal", "tax audit", "civic"],
    ["morosidad", "late payment / delinquency", "basics"],
    ["recargo", "surcharge", "shopping"],
    ["interés compuesto", "compound interest", "basics"],
    ["interés simple", "simple interest", "basics"],
    ["inversión diversificada", "diversified investment", "basics"],
    ["volatilidad", "volatility (markets)", "basics"],
    ["mercado bajista", "bear market", "basics"],
    ["mercado alcista", "bull market", "basics"],
    ["dividendo", "dividend", "basics"],
    ["acción cotizada", "listed stock", "basics"],
    ["bono del Estado", "government bond", "basics"],
    ["fondo indexado", "index fund", "basics"],
    ["criptomoneda", "cryptocurrency", "basics"],
    ["billetera digital", "digital wallet", "tech"],
    ["cadena de bloques", "blockchain", "tech"],
    ["contrato inteligente", "smart contract", "tech"],
    ["token no fungible", "non-fungible token (NFT)", "tech"],
    ["estafa piramidal", "pyramid scheme", "basics"],
    ["lavado de dinero", "money laundering", "civic"],
    ["blanqueo de capitales", "money laundering (formal)", "civic"],
    ["paraíso fiscal", "tax haven", "civic"],
    ["evasión fiscal", "tax evasion", "civic"],
    ["elusión fiscal", "tax avoidance (legal gray)", "civic"],
  ];

  for (const [es, en, tag] of vocabExtraV2) window.WORD_BANK.push({ es, en, tag });

  // Body parts, nervous system, and skeletal muscle (main vocabulary deck).
  const anatomyExtraV1 = [
    // Body — head & senses
    ["oreja", "ear (outer ear)", "body"],
    ["oído", "ear / sense of hearing", "body"],
    ["ojos", "eyes", "body"],
    ["párpado", "eyelid", "body"],
    ["pupila", "pupil (of the eye)", "body"],
    ["cejas", "eyebrows", "body"],
    ["pestañas", "eyelashes", "body"],
    ["frente", "forehead", "body"],
    ["mejilla", "cheek", "body"],
    ["barbilla", "chin", "body"],
    ["labio", "lip", "body"],
    ["mandíbula", "jaw / mandible", "body"],
    ["axila", "armpit", "body"],
    ["costilla", "rib", "body"],
    ["espalda baja", "lower back", "body"],
    ["columna vertebral", "spine / spinal column", "body"],
    ["cintura", "waist", "body"],
    ["ombligo", "belly button / navel", "body"],
    ["ingle", "groin", "body"],
    ["muslo", "thigh", "body"],
    ["pantorrilla", "calf (lower leg)", "body"],
    ["talón", "heel", "body"],
    ["arco del pie", "arch of the foot", "body"],
    ["palma", "palm (of the hand)", "body"],
    ["nudillo", "knuckle", "body"],
    ["pulgar", "thumb", "body"],
    ["dedo índice", "index finger", "body"],
    ["dedo medio", "middle finger", "body"],
    ["dedo anular", "ring finger", "body"],
    ["meñique", "pinky / little finger", "body"],
    ["dedo del pie", "toe", "body"],
    ["uñas", "fingernails / toenails", "body"],
    ["vesícula biliar", "gallbladder", "body"],
    ["intestino", "intestine", "body"],
    ["vejiga", "bladder (urinary)", "body"],

    // Brain & neurons
    ["neurona", "neuron", "neuro"],
    ["sinapsis", "synapse", "neuro"],
    ["axón", "axon", "neuro"],
    ["dendrita", "dendrite", "neuro"],
    ["neurotransmisor", "neurotransmitter", "neuro"],
    ["corteza cerebral", "cerebral cortex", "neuro"],
    ["lóbulo frontal", "frontal lobe", "neuro"],
    ["lóbulo temporal", "temporal lobe", "neuro"],
    ["lóbulo parietal", "parietal lobe", "neuro"],
    ["lóbulo occipital", "occipital lobe", "neuro"],
    ["cerebelo", "cerebellum", "neuro"],
    ["tronco encefálico", "brainstem", "neuro"],
    ["tálamo", "thalamus", "neuro"],
    ["hipotálamo", "hypothalamus", "neuro"],
    ["hipocampo", "hippocampus", "neuro"],
    ["sustancia gris", "gray matter", "neuro"],
    ["sustancia blanca", "white matter", "neuro"],
    ["médula espinal", "spinal cord", "neuro"],
    ["nervio", "nerve", "neuro"],
    ["glía", "glia (support cells)", "neuro"],
    ["barra hematoencefálica", "blood-brain barrier", "neuro"],

    // Muscles (named groups & general)
    ["músculo", "muscle", "muscles"],
    ["músculo esquelético", "skeletal muscle", "muscles"],
    ["tendón", "tendon", "muscles"],
    ["fascia", "fascia", "muscles"],
    ["bíceps braquial", "biceps (arm)", "muscles"],
    ["tríceps braquial", "triceps (arm)", "muscles"],
    ["cuádriceps", "quadriceps", "muscles"],
    ["isquiotibiales", "hamstrings", "muscles"],
    ["aductores", "adductors (inner thigh)", "muscles"],
    ["abductores", "abductors", "muscles"],
    ["glúteo mayor", "gluteus maximus", "muscles"],
    ["glúteo medio", "gluteus medius", "muscles"],
    ["psoas", "psoas (hip flexor)", "muscles"],
    ["recto abdominal", "rectus abdominis", "muscles"],
    ["oblicuo externo", "external oblique", "muscles"],
    ["oblicuo interno", "internal oblique", "muscles"],
    ["transverso del abdomen", "transversus abdominis", "muscles"],
    ["deltoides", "deltoid (shoulder muscle)", "muscles"],
    ["trapecio", "trapezius", "muscles"],
    ["dorsal ancho", "latissimus dorsi", "muscles"],
    ["infraespinoso", "infraspinatus", "muscles"],
    ["redondo mayor", "teres major", "muscles"],
    ["pectoral mayor", "pectoralis major", "muscles"],
    ["pectoral menor", "pectoralis minor", "muscles"],
    ["serrato anterior", "serratus anterior", "muscles"],
    ["braquial", "brachialis", "muscles"],
    ["braquiorradial", "brachioradialis", "muscles"],
    ["gastrocnemio", "gastrocnemius (calf)", "muscles"],
    ["sóleo", "soleus (deep calf)", "muscles"],
    ["tibial anterior", "tibialis anterior", "muscles"],
    ["peroneo largo", "fibularis longus", "muscles"],
    ["gemelos", "calf muscles (gastrocnemius pair)", "muscles"],
    ["masetero", "masseter (jaw muscle)", "muscles"],
    ["temporal", "temporalis (jaw muscle)", "muscles"],
    ["esternocleidomastoideo", "sternocleidomastoid (neck)", "muscles"],
    ["diafragma", "diaphragm", "muscles"],
  ];

  for (const [es, en, tag] of anatomyExtraV1) window.WORD_BANK.push({ es, en, tag });

  // De-duplicate (same Spanish) while keeping the first occurrence.
  const seen = new Set();
  window.WORD_BANK = window.WORD_BANK.filter((w) => {
    const key = String(w.es).trim().toLowerCase();
    if (!key) return false;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  try {
    if (typeof window.dispatchEvent === "function") {
      window.dispatchEvent(new Event("wordbankready"));
    }
  } catch (e) {
    /* ignore */
  }
})();

